### ISSUE TITLE
onDeactivation is missing in npm package bundle

### ISSUE THREAD

**Issue by vad3x** [remojansen/InversifyJS#1380]
I's trying to implement [Deactivation Handler](https://github.com/inversify/InversifyJS/blob/master/wiki/deactivation_handler.md) but found that many methods, including [onDeactivation](https://github.com/inversify/InversifyJS/blob/master/src/container/container.ts#L239) are missing in npm package (5.1.1).

When I build bundle from inversify source code, I get the methods bundled.

## Expected Behavior
Deactivation methods from source code appear in npm package.

## Current Behavior
Some methods are missing.

## Possible Solution
Build and publish new version.

**Comment by notaphplover** [comment]
This issue was already solved, closing as completed
