### ISSUE TITLE
@postConstruct docs say async is possible, but it throws exception

### ISSUE THREAD

**Issue by ideasculptor** [remojansen/InversifyJS#1389]
The documentation for @postConstruct() (https://github.com/inversify/InversifyJS/blob/master/wiki/post_construct.md) explicitly states that the method can be synchronous or asynchronous.  No example is provided and when I attempt to use it on an async function, I get an exception that appears to be because it is an async methof: 

```
  error: TypeError: Cannot convert a Symbol value to a string
      at Object.LAZY_IN_SYNC (/Users/sgendler/src/yalochat/customer-service-ts/node_modules/inversify/lib/constants/error_msgs.js:25:80)
      at Container._getButThrowIfAsync (/Users/sgendler/src/yalochat/customer-service-ts/node_modules/inversify/lib/container/container.js:595:40)
      at Container.get (/Users/sgendler/src/yalochat/customer-service-ts/node_modules/inversify/lib/container/container.js:374:21)
```
class is annotated via the following code:
`decorate(postConstruct(), client.Producer.prototype, "connect");`

and the connect method looks like this:
`connect(): Promise<void>;`

Is there something I'm missing about using that decorator with an async function?

**Comment by ideasculptor** [comment]
never mind.  getAsync() fixed the problem

**Comment by Bogatinovski** [comment]
@ideasculptor I am having the same issue. What do you mean by getAsync()? Where can I find this method?

**Comment by jusstes** [comment]
> @ideasculptor I am having the same issue. What do you mean by getAsync()? Where can I find this method?

[getAsync()](https://github.com/inversify/InversifyJS/blob/master/wiki/container_api.md#containergetasynctserviceidentifier-interfacesserviceidentifiert-promiset)
it's probably no longer relevant, but just in case it might help someone else
