### ISSUE TITLE
[inversify-express-utils] Latest version is failing to build

### ISSUE THREAD

**Issue by ChaloJaldi** [remojansen/InversifyJS#1392]
Our builds have started failing due to latest inversify-express-utils not build properly

## Expected Behavior
express-utils should not throw build errors 

Current version: Inversify-express-utils@6.3.2
Latest version: Inversify-express-utils@6.4.3

## Your Environment
* Typescript version: 3.8.3
* Node version: v12.13.0
* Windows 10 Pro

# Stack trace

> tsc
> 
> node_modules/inversify-express-utils/node_modules/inversify/lib/annotation/injectable.d.ts:1:52 - error TS1005: ',' expected.
> 
> 1 declare function injectable(): <T extends abstract new (...args: never) => unknown>(target: 
> T) => T;
>                                                      ~~~
> node_modules/inversify-express-utils/node_modules/inversify/lib/annotation/injectable.d.ts:1:83 - error TS1144: '{' or ';' expected.
> 
> 1 declare function injectable(): <T extends abstract new (...args: never) => unknown>(target: 
> T) => T;
>                                                                                     ~
> node_modules/inversify-express-utils/node_modules/inversify/lib/annotation/injectable.d.ts:1:91 - error TS1005: ')' expected.
> 
> 1 declare function injectable(): <T extends abstract new (...args: never) => unknown>(target: 
> T) => T;
>                                                                                             ~ 
> node_modules/inversify-express-utils/node_modules/inversify/lib/annotation/injectable.d.ts:1:94 - error TS1005: ';' expected.
> 
> 1 declare function injectable(): <T extends abstract new (...args: never) => unknown>(target: 
> T) => T;
>   
> 
> node_modules/inversify-express-utils/node_modules/inversify/lib/annotation/injectable.d.ts:1:96 - error TS1128: Declaration or statement expected.
> 
> 1 declare function injectable(): <T extends abstract new (...args: never) => unknown>(target: 
> T) => T;

**Comment by dcavanagh** [comment]
@GlassHill will you please provide some example code and your tsconfig.json.

**Comment by ChaloJaldi** [comment]
Solved the issue locally

Download the latest typescript version, globally (npm install -g typescript) and also for the project.
Download the latest inversify & inversify-express-utils packages

This caused the package to start working for us.
