### ISSUE TITLE
SWC compatibility

### ISSUE THREAD

**Issue by GuillaumeCisco** [remojansen/InversifyJS#1403]
Is inversify compatible with SWC?
From our tests, it looks like the `@inject(...)` decorators are not correctly transpiled.

## Expected Behavior

Works with swc

## Current Behavior

`@inject` decorators seems bypassed.

## Steps to Reproduce (for bugs)

1. compile you inversify app with swc

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

# Stack trace

**Comment by HeadFox** [comment]
Just define https://swc.rs/docs/configuration/compilation#jsctransformdecoratormetadata in your .swcrc file

**Comment by GuillaumeCisco** [comment]
Thank you for your reply.
We did use this configuration without success.
Any ideas?

**Comment by HeadFox** [comment]
Can you give me more information ? Bundler used, config file, etc...

**Comment by leonardssh** [comment]
@GuillaumeCisco try this.
```jsonc
{
	jsc: {
		target: 'es2020',
		parser: {
			syntax: 'typescript',
			dynamicImport: true,
			decorators: true
		},
		transform: {
			legacyDecorator: true,
			decoratorMetadata: true
		},
		externalHelpers: true,
		keepClassNames: true,
		loose: true
	}
}
```

@HeadFox for bundling, I recommend using rollup, along with the [rollup-plugin-swc3](https://github.com/SukkaW/rollup-plugin-swc) & [rollup-plugin-tsconfig-paths](https://github.com/lightyen/typescript-paths/tree/main/packages/rollup-plugin-tsconfig-paths)

Some config:
```jsonc
import { swc } from 'rollup-plugin-swc3';
import { tsConfigPaths } from 'rollup-plugin-tsconfig-paths';
import { nodeResolve } from '@rollup/plugin-node-resolve';

// bypass errors thrown by inversify
const onwarn = (msg, warn) => {
	if (!/Circular|The 'this' keyword/.test(msg)) {
		warn(msg);
	}
};

// ...
{
	input: INPUT_FILE,
	output: {
		file: OUTPUT_FILE,
		format: 'cjs'
	},
	plugins: [
		tsConfigPaths({ tsConfigPath: PATH_TO_TSCONFIG }),
		nodeResolve(),
		swc({
			tsconfig: PATH_TO_TSCONFIG,
			minify: false, // set to true to minify
			jsc: {
				target: 'es2020',
				parser: {
					syntax: 'typescript',
					dynamicImport: true,
					decorators: true
				},
				transform: {
					legacyDecorator: true,
					decoratorMetadata: true
				},
				externalHelpers: true,
				keepClassNames: true,
				loose: true
			}
		})
	],
	onwarn
};
```

**Comment by kristiegiles** [comment]
@[GuillaumeCisco](https://github.com/GuillaumeCisco) did you find a solution? I am having the same issue and the `.swcrc` config @[LeonardSSH](https://github.com/LeonardSSH) suggested didn't work for me, either. 

I am using Next.js 12 and am attempting to migrate from babel to swc. I get `Attempted import error:` on everything defined with the `@inject()` decorators when running `next build`.

**Comment by HeadFox** [comment]
@kristiegiles Next12 disabled .swcrc load. But support for emitDecoratorMetadata will be enabled if specified in tsconfig in next Next.js release --> https://github.com/vercel/next.js/pull/32914

**Comment by kristiegiles** [comment]
> @kristiegiles Next12 disabled .swcrc load. But support for emitDecoratorMetadata will be enabled if specified in tsconfig in next Next.js release --> [vercel/next.js#32914](https://github.com/vercel/next.js/pull/32914)

Thanks! I also tried it without the .swcrc, and that didn't help. I am using Next 12.0.11-canary.11, and I do have `"emitDecoratorMetadata": true` and `experimentalDecorators": true` in my tsconfig. It should work with the latest canary version, right?

**Comment by HeadFox** [comment]
Normally yes. With also reflect-metadata installed

**Comment by sannajammeh** [comment]
> > @kristiegiles Next12 disabled .swcrc load. But support for emitDecoratorMetadata will be enabled if specified in tsconfig in next Next.js release --> [vercel/next.js#32914](https://github.com/vercel/next.js/pull/32914)
> 
> Thanks! I also tried it without the .swcrc, and that didn't help. I am using Next 12.0.11-canary.11, and I do have `"emitDecoratorMetadata": true` and `experimentalDecorators": true` in my tsconfig. It should work with the latest canary version, right?

That's correct!

**Comment by HeadFox** [comment]
@GuillaumeCisco can you close this Pr ? :)

**Comment by gb-jos** [comment]
have used inversify with swc and it works fine for me

**Comment by ko22009** [comment]
Problem about transpilation, you need set "target" es2015 or higher in your .swcrc config file.

**Comment by jantoine1** [comment]
The link provided in the first comment worked great. Thank you!!!

**Comment by notaphplover** [comment]
Closing as `inversify` seems to be compatible with `swc`. I honestly think `inversify` should be compatible with `swc` as long as `tsc` does not complain. `swc` is the one which should be compatible with any valid `typescript` source code.
