### ISSUE TITLE
Application dies with `INVALID_BINDING_TYPE` after upgrading to v6

### ISSUE THREAD

**Issue by oliversalzburg** [remojansen/InversifyJS#1405]
After upgrading to invesify@6, some of my test suites fail, referencing `INVALID_BINDING_TYPE`:

```
   Invalid binding type: Symbol(Broker)
      56 |   const em = orm.em.fork();
      57 |
    > 58 |   const broker = container.get<Broker>(BrokerType);
```

## Expected Behavior

I expect my test suite to pass, as it did with inversify@v5.

## Current Behavior

The binding is detected as being of an invalid _type_, which is confusing as it mentions a Symbol in the same context.

## Possible Solution

Looking at the [relevant source](https://github.com/inversify/InversifyJS/blob/772ea8ef53b17ac00a35df45d00bfc2f1ca53d07/src/utils/binding_utils.ts#L33-L39) explains what is going on.

The binding that is causing the problem is:
```ts
bind(BrokerType).toConstantValue(null);
```

## Steps to Reproduce (for bugs)

1. Bind something to `null`

## Context

Binding to `undefined` works just as well for my case. The introduced fault just feels unfortunate.

## Your Environment

* Version used: latest v5
* Environment name and version (e.g. Chrome 39, node.js 5.4): NodeJS 16.x
* Operating System and version (desktop or mobile): Desktop
* Link to your project:

**Comment by jkhmtx** [comment]
Hello!

I'm sorry to say it, but this represents one of the breaking changes from v5 => v6. It appears that since you have a workaround (?) (I agree that binding to `undefined` is quite odd to be allowed, as well), I think it is fair to say that this is edge case should not be supported. I recommend closing this issue @PodaruDragos 

I am curious, do you mind sharing why you want to bind a dependency to `null`?

**Comment by oliversalzburg** [comment]
We have optional components, like for distributed tracing, that we don't load in all scenarios and the consumers accept `null` as a valid value that implies that tracing should be skipped. It felt like a valid approach at the time, but I can also imagine different solutions. I'll be fine if this issue is closed :)

However, I feel like the chosen solution in the inversify code base is needlessly fragile. If you want to use a safe default value that signals a missing binding, use a unique symbol that no consumer has access to. Repurposing `null` for this behavior seems needlessly limiting. But I'm happy to accept that my attempt to use `null` this way was wrong all along :D

**Comment by jkhmtx** [comment]
It sounds to me like your use case falls more into the capability that is afforded by the [optional dependency decorator](https://github.com/inversify/InversifyJS/blob/master/wiki/optional_dependencies.md). Any _unbound_ dependency that is marked as `@optional` in a dependent will not cause an error during dependency resolution, and its value in the dependent will be `undefined`.

**Comment by oliversalzburg** [comment]
I actually was wrong regarding the use case where this is used. It's actually a test suite helper that makes use of this behavior.

I don't see how I would apply the optional dependency approach you pointed out to this `container.get` call, but I can just as well catch the error about the missing binding and then just do what the test helper does.

As this was undesired behavior to begin with, I'd say there's no further need to debate about the usefulness. Thanks for your help :)
