### ISSUE TITLE
Injecting Server level middleware with dependencies throws error on dependency

### ISSUE THREAD

**Issue by jsmilovic** [remojansen/InversifyJS#1417]
I wrote a middleware for injecting a tenant request, it works fine injecting it into a controller, but not at the server level.  I get 
Cannot read properties of undefined (reading '_logger')
I assume it's because the logger is injected on the class but I'm trying to pass in just the handler.  I'm not sure how this pattern is intended to work

## Expected Behavior

`container.bind(TYPES.TenantMiddleware).to(TenantMiddleware);
`

```
@injectable()
export class TenantMiddleware extends BaseMiddleware {

    @inject(TYPES.Logger) private readonly _logger: Logger;
    public handler(
        req: express.Request,
        res: express.Response,
        next: express.NextFunction
    ) {
        const host = req.get('host');
        this._logger.log("info", `host: ${host}`);
        req.tenant = host;
        next();
    }
}

```
`app.use(container.get<TenantMiddleware>(TYPES.TenantMiddleware).handler);
`

# Stack trace

**Comment by magicmatatjahu** [comment]
@jsmilovic Hi!

> I assume it's because the logger is injected on the class but I'm trying to pass in just the handler. I'm not sure how this pattern is intended to work

You're right. You pass only handler without `this` context, so then you have error that `log` function doesn't exist because `_logger` is undefined.

You should first retrieve middleware and then pass handler with injected `this`:

```
const middleware = container.get<TenantMiddleware>(TYPES.TenantMiddleware);
app.use(middleware.handler.bind(middleware));
```

**Comment by jsmilovic** [comment]
@magicmatatjahu Wow, that makes so much sense!  Really appreciate the help, thanks for the reminder that bind exists 😂
