### ISSUE TITLE
Failed to parse source map from '.../node_modules/inversify/src/utils/serialization.ts' file: Error: ENOENT: no such file or directory, open '.../node_modules/inversify/src/utils/serialization.ts'

### ISSUE THREAD

**Issue by ds1371dani** [remojansen/InversifyJS#1421]
## Expected Behavior
No sourcemap warnings should be displayed.

## Current Behavior
Files referred inside `.js.map` files are not included in the build.

## Possible Solution
`sources` section of source map files refer to src directory which is not included in the build. I think content of sources should become inline (`sourcesContent`) so this warning goes away. This can be done by adding `"inlineSources": true,` to tsconfig.json file

## Steps to Reproduce (for bugs)
Create any project with create-react-app (version ^5.0.0)

## Your Environment

* Version used: ^5.1.0, ^6.0.1
* Environment name and version (e.g. Firefox 96.0, node.js 16.13.2):
* Operating System and version (desktop or mobile): linux ubuntu 20.04.3

It would be great if this is implemented in 5.x.x version too because I'm not using this package directly and the package that I'm using uses version `^5.0.1` of inversify.

# Stack trace
```
WARNING in ./node_modules/inversify/lib/utils/serialization.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from './node_modules/inversify/src/utils/serialization.ts' file: Error: ENOENT: no such file or directory, open './node_modules/inversify/src/utils/serialization.ts'
```

**Comment by ds1371dani** [comment]
I just found a pull request related to this https://github.com/inversify/InversifyJS/pull/1412

Source maps should either be removed completely (as in the pull request) or change `tsconfig.json` to add src to `.js.map` files to get rid of the warnings

**Comment by jkhmtx** [comment]
@PodaruDragos The linked PR is merged so this issue is now resolved.

**Comment by jkhmtx** [comment]
@PodaruDragos @ds1371dani 

I now see that this change has been merged to the master branch, but we have not done a release with the changes yet.

Here is another issue tracking this same situation by the way: https://github.com/inversify/InversifyJS/issues/1408

I recommend that this issue remain closed (since it is a duplicate), but we should make sure to do a patch release soon to allow this fix to go to npm.
