### ISSUE TITLE
inversify-restify-utils vulnerability

### ISSUE THREAD

**Issue by acommodari** [remojansen/InversifyJS#1432]
The `inversify-restify-utils` library has a high level vulnerability because of one of its dependencies.

## Expected Behavior

No vulnerabilities within the package.

## Current Behavior

Getting a high level security vulnerability because of the gulp-debug dependency.

## Possible Solution

It seems this vulnerability is caused by `gulp-debug`.
There is no new version available for that package that fixes the vulnerabilities right now.
But according to the `README.md` it seems like `gulp-debug` should be in `devDependencies`. Moving it to `devDependencies` should in turn fix the vulnerability issue since only a packages dependencies are installed when someone installs said package.
It should be a trivial PR to move `gulp-debug` over to `devDependencies`.

## Steps to Reproduce (for bugs)

1. run `npm i`

## Context

This affects us because it exposes our repo to vulnerabilities.

## Your Environment

* Version used: 3.4.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): node@16 and npm@8
* Operating System and version (desktop or mobile): macOS 11.6.2

# Stack trace

```sh
glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install inversify-restify-utils@3.3.1, which is a breaking change
node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/chokidar
    glob-watcher  >=3.0.0
    Depends on vulnerable versions of chokidar
    node_modules/glob-watcher
      gulp  >=4.0.0
      Depends on vulnerable versions of glob-watcher
      node_modules/gulp
        gulp-debug  >=4.0.0
        Depends on vulnerable versions of gulp
        node_modules/gulp-debug
          inversify-restify-utils  >=3.4.0
          Depends on vulnerable versions of gulp-debug
          node_modules/inversify-restify-utils
  glob-stream  5.3.0 - 6.1.0
  Depends on vulnerable versions of glob-parent
  node_modules/glob-stream
    vinyl-fs  >=2.4.2
    Depends on vulnerable versions of glob-stream
    node_modules/vinyl-fs
```

**Comment by acommodari** [comment]
Looking at `package.json` more closely I've found some other weird behaviour.

1. Why is `restify` dependency an exact version? This will cause dependency duplication in users `node_modules` files which might cause errors at worst and bloats `node_modules` at the very least.
2. Why are `inversify` and `restify` not just set as required `peerDependencies`? They are both needed for this package to work and it is implied that if someone is installing this package they are using both of these. They should be moved to `peerDependencies` with a very loose version requirements. (This might warrant a major version update just in case)

**Comment by acommodari** [comment]
Also looking more into the code `gulp-debug` does not even seem to be used?
Also `run-sequence` is defined in `gulpfile.js` but also never used.

**Comment by jkhmtx** [comment]
> Also looking more into the code gulp-debug does not even seem to be used?

More than likely, it was included by mistake during a different unit of work's debugging effort.

> Also run-sequence is defined in gulpfile.js but also never used.

A great find!

@acommodari There is a repo for [inversify-restify-utils](https://github.com/inversify/inversify-restify-utils). If you would be so kind as to open a PR for removing the `run-sequence` and `gulp-debug` dependencies, I would be happy to help you get it merged.

> Why are inversify and restify not just set as required peerDependencies? They are both needed for this package to work and it is implied that if someone is installing this package they are using both of these. They should be moved to peerDependencies with a very loose version requirements. (This might warrant a major version update just in case)

Philosophically, I agree with you, but I would consider this a separate issue. Please feel free to open an issue there if you would like to chase this down!

> Why is restify dependency an exact version? This will cause dependency duplication in users node_modules files which might cause errors at worst and bloats node_modules at the very least.

This is something that I don't have a solid answer for. Again, this may be worth considering in a different issue's context in that repo. 🙏

**Comment by jkhmtx** [comment]
I'm going to ask for this issue to be closed for now as it does not pertain to this repo, but if you do decide to leave a PR @acommodari, please feel free to link this issue.

**Comment by acommodari** [comment]
@jakehamtexas  I ended up finally creating a [PR](https://github.com/inversify/inversify-restify-utils/pull/351)
