### ISSUE TITLE
InversifyJS Interfaces Provider issue with TypeScript

### ISSUE THREAD

**Issue by Vinothpugal** [remojansen/InversifyJS#1433]
While trying to upgrade inversify npm module 2.0.0.rc.1 into the latest version (6.0.1)

I'm facing below issue after upgrading to latest version 6.0.1.

**Sample Code:**
```
@injectable()
class Sample implements ISample {
public databaseProvider: interfaces.Provider<Database.IDatabase>;
public constructor( 
	    @inject(Symbol("Provider<Database.IDatabase>")) databaseProvider:  interfaces.Provider<Database.IDatabase>
    ) {
        this.databaseProvider= databaseProvider;
    }

public getDocuments(){
  this.databaseProvider().then((database) => {
 //code logic
  })
 }
}
```
**Error:**
`error TS2339: Property 'then' does exist on type Promise<Monog.Db> | ((..args: any[]) => Promise<Mongo.Db>)`

**Expected Behavior**
Provider object should allow Promise functionality. 

**Current Behavior**
Promise functionality not supporting. 

## Context
After migrating 2.0.0.rc.1 into the latest version (6.0.1) we could reproduce this issue.

Node Version: 16
Typescript version: 4.4.4
Inversify: 6.0.1

**Comment by jkhmtx** [comment]
Hello!

This type signature is meant to enable [provider partial application](https://github.com/inversify/InversifyJS/blob/master/wiki/provider_injection.md#provider-partial-application). It is quite tricky to get this sort of type signature "automatic" to the use case, where the type system is aware of your definition of the provider as not using partial application.

For now I recommend using the `as` assertion, as in:

```typescript
public getDocuments(){
  (this.databaseProvider() as Promise<Mongo.Db>).then((database) => {
   //code logic
  })
 }
}
```

It would be interesting to think of how to solve this problem in a way that would make the provider type automatically resolvable for Typescript according to the binding definition that you provide, but I think it would require some world class Typescript skills, or language features of TS that do not exist yet.

Overall I would estimate that this is a common problem, so perhaps this direction should be included in the docs for provider.

What do you think @PodaruDragos ?

**Comment by PodaruDragos** [comment]
> **Expected Behavior**
> Provider object should allow Promise functionality.

And it does, this is just a types thing as @jakehamtexas said. Casting is a viable solution here. Closing this for now but feel free to reopen if it's not the case.
