### ISSUE TITLE
Container onActivation and onDeactivation handlers *intentionally* not running when unloading the container module - Why?

### ISSUE THREAD

**Issue by wi-ski** [remojansen/InversifyJS#1438]
When loading/unloading a container module, I would expect the onActivation/onDeactivation handlers to run.

This test outlines how that's not the expectation: https://github.com/inversify/InversifyJS/blob/772ea8ef53b17ac00a35df45d00bfc2f1ca53d07/test/container/container_module.test.ts#L244-L263

Very succinct 💔 

Is that really the intention? 

## Expected Behavior
The onActivation/onDeactivation handlers are ran, causing the linked tests to fail.

## Current Behavior
The onActivation/onDeactivation handlers are NOT ran, causing the linked tests to fail.

## Possible Solution
We invoke those handlers when unmounting the modules!

## Steps to Reproduce (for bugs)
The tests outline this <3

## Context
I want to group some dependencies and have them load/unload together/separately.

## Your Environment

* Version used: Latest
* Environment name and version (e.g. Chrome 39, node.js 5.4): TypeScript (Latest)
* Operating System and version (desktop or mobile): Mac OS
* Link to your project: Private

# Stack trace
N/A

**Comment by jkhmtx** [comment]
> When loading/unloading a container module, I would expect the onActivation/onDeactivation handlers to run.

The [docs](https://github.com/inversify/InversifyJS/blob/master/wiki/container_modules.md) specify that the behavior of container modules and activation/deactivation handlers is the following:

> When a container module is unloaded from a Container the bindings added by that container will be removed and the [deactivation process](https://github.com/inversify/InversifyJS/blob/master/wiki/deactivation_handler.md) will occur for each of them. Container deactivation and [activation handlers](https://github.com/inversify/InversifyJS/blob/master/wiki/activation_handler.md) will also be removed.

This means that the deactivation/activation handlers are applied to the container on which the module is loaded, and if the module is unloaded before the container is activated, this means that the handlers are likewise removed.

I admit that the documentation is not 100% clear about the state of module handlers at the time of loading the module, it could be a nice way to improve clarity if somebody were to add some more context about that per this explanation.

Does that make sense?

**Comment by jkhmtx** [comment]
Happy to continue the conversation for the sake of providing clarity, but as this is intended behavior, I recommend closure of this issue.
