### ISSUE TITLE
The most rubbish official document!

### ISSUE THREAD

**Issue by 9a-aaaaaaaa** [remojansen/InversifyJS#1444]
The most rubbish official document, shit! It's hard to understand. It's inexplicable

**Comment by PodaruDragos** [comment]
I'm sorry you feel that way. What do you suggest we do about it ?

**Comment by jkhmtx** [comment]
> It's inexplicable

Feel free to make some comments or a PR expressing how you think that they are difficult to understand or could be improved. _In a separate issue._

Whinging and using profanity like this are not okay, though.
