### ISSUE TITLE
TYPES must be in own file!?

### ISSUE THREAD

**Issue by andrecadete** [remojansen/InversifyJS#1455]
Hi, not really a bug report, just to see if you are aware since this is not obvious in the docs. As title states.

In fact I cannot get this to work unless the TYPES are explicitly declared and exported in their own file. For example, if the TYPES are exported and declared in the same file as the Container extension class, we will get something: "TypeError: Cannot read property 'DynamoDB' of undefined", where `undefined` are our TYPES.

Please let me know if this is expected behavior and if so I'll open a PR to improve the docs' clarity in that sense.

Thanks

**Comment by AkshayJangid** [comment]
Hey, I'll be more then happy to make a PR for this. Let me know if i can help here, but lets add this ASAP.

**Comment by shellscape** [comment]
@Jameskmonger given your comments here https://github.com/inversify/InversifyJS/pull/1546#issuecomment-1789488948, this is probably worthy of a look given its age, no?

**Comment by notaphplover** [comment]
I don't see how this is related to inversify. After having a look at #1179, `Types` are already imported from their own file. I'm closing the issue now. If you want feel free to provide a minimum reproduction code in a [codesandbox](https://codesandbox.io) or a reproduction repo.

**Comment by shellscape** [comment]
A year and 5 days!
