### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by nickraphael** [remojansen/InversifyJS#1456]
## Expected Behavior
Unit tests should be able to inject dependencies

## Current Behavior
I'm getting this error when running the tests...

C:\xxx\src\app\services\auth\JWTAuthentication.service.ts:31 constructor(@(0, _inversify.inject)(_ICookieStorage.ICookieStorageService$) ^ SyntaxError: Invalid or unexpected token

So it seems to me that it can't resolve the @inject in my constructor...

constructor(@inject(ICookieStorageService$) cookieStorageService: ICookieStorageService) {
    ...code here
  }
In the root index.ts of my application, I wrap the application in

import { Provider } from 'inversify-react';
<Provider container={container}>
    ...the app
</Provider>
and container is defined in inversify.config.ts.

Obviously this doesn't get wired up when running tests. I'm not sure how to fix my issue. There is almost zero information out there on unit testing with inversify.

I've tried putting import 'reflect-metadata'; everywhere. That didn't help. Also, I don't use babel.

I must need to define a mock for the dependency. But no matter what I try, it doesn't seem to understand the @inject bit.

**Comment by notaphplover** [comment]
This is probably due to not enabling `experimentalDecorators` option in your typescript config. I'm closing the issue now, feel free to provide a minimum code example in a [code sandbox](https://codesandbox.io) or a repro repository.
