### ISSUE TITLE
Adding routes from already existing express application to setConfig with app.use()

### ISSUE THREAD

**Issue by pryme0** [remojansen/InversifyJS#1470]
I want to clarify if it is possible to add routes from an already existing express application to setConfig just like you would do with a normal express application .
something like 

`  server.setConfig((app) => {
    app.use("/scripts", AuthRoute);
  })`

where AuthRoute is an express router

**Comment by PodaruDragos** [comment]
I believe this should be possible. yes.

**Comment by pryme0** [comment]
Yeah it is ...tried it and it worked...thanks @PodaruDragos 

I will close the issue now
