### ISSUE TITLE
Project maintenance.

### ISSUE THREAD

**Issue by Rizialdi** [remojansen/InversifyJS#1473]
Hi everyone,
I hope you are fine.

It's not an issue, but a simple question since I just found about this project.

I'm wondering why that repo seems to no longer be under active development ?
Is the project complete or is it just a lack of maintainer that explains it ?

Best.

**Comment by PodaruDragos** [comment]
Hello @Rizialdi, as you can see in the pinned issue [here](https://github.com/inversify/InversifyJS/issues/1426) we are lacking maintainers.

Nothing more to add to this. If you want to support this project you can get involved also.

**Comment by Rizialdi** [comment]
I see. Thank you for your answer @PodaruDragos.
That situation is pretty sad. I was just exploring so I did not plan to get involved. Hope I may get involved in the future.
