### ISSUE TITLE
Need decorator which first letter is capitalized.

### ISSUE THREAD

**Issue by yeongjet** [remojansen/InversifyJS#1474]
In my project, first letter of all decorators are capitalized but inversify so I have to translate it. I don't know if there are standards about decorator naming, but I suggest to provide alias which first letter is capitalized of existent decorators, thanks.

**Comment by remojansen** [comment]
I understand your need, but I recommend not changing the public interface. Adding an alias may seem harmless, but it can lead to confusion (especially for first-time users). I think it would negatively impact the developer experience.

You can declare an util in your project to achieve this:

```ts
// capitalize-object.ts

type CapProps<T> = {
    [P in keyof T & string as Capitalize<P>]: T[P]
};

interface KeyObj {
  [key: string]: any;
}

export function capitalizeObject<T extends KeyObj>(obj: T): CapProps<T> {
    const cap: CapProps<T> = Object.keys(obj).reduce((prev, curr) => {
        const capCurr = curr.charAt(0).toUpperCase() + curr.slice(1);
        prev[capCurr] = obj[curr];
        return prev;
    }, {} as any);
    return cap;
}
```

You can then use the util to create a new module:

```ts
// decorators.ts
import * as Inversify from "inversify";
import { capitalizeObject } from "./capitalize-object";

export const { Injectable, Inject } = capitalizeObject(Inversify);
```
Finally, you can use your module:

```ts
// test.ts
import { Injectable, Inject} from "./decorators.ts"
```

**Comment by PodaruDragos** [comment]
> 

Hello @remojansen, welcome back. We are really missing you in the project.

As a faster approach I would also like to suggest this: 
`import { inject as Inject, injectable as Injectable } from 'inversify';`

**Comment by yeongjet** [comment]
Thanks for answer!

**Comment by remojansen** [comment]
@PodaruDragos, thanks for your answer; much better than mine! Sorry, I cannot work on the project but I do check how things are going on every now and then. Thanks a lot for keeping the project alive!
