### ISSUE TITLE
fields at innjectable classes work as static

### ISSUE THREAD

**Issue by Nau077** [remojansen/InversifyJS#1479]
## Expected Behavior
classess fields must work as usuasl javascript classes fields.
```

@injectable()
export class SomeClass implements ISomeClass {
  private some_array;
 
...

}
```

"this.some_array" field as result shoudnot work as "static some_array" - but some_array`s behaviour is simillar to the static properties

## Current Behavior
At the some calls of this injectable class I can see in simillar fields as "some_array" data from previos injectable class calls.

## Possible Solution
Fix this strange behaviour. Make fields in injectables classes work as simple fields in javascripts, not as static fields.

 
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
node v14.19.1
"inversify": "^5.0.5"
"ts-node": "^10.9.1",
"typescript": "^4.7.4"

**Comment by notaphplover** [comment]
Closing as the issue lacks of a minimum reproduction code sample, like a code sandbox or a reproduction repository.
