### ISSUE TITLE
No matching bindings found for serviceIdentifier: Array

### ISSUE THREAD

**Issue by illia-halchun** [remojansen/InversifyJS#1495]
I am trying to build game using inversifyJS
An issue occurs when i try to inject some dependency to the class using @inject() method ( /view/screen.view.ts on the 15th line)
My app (repo: https://github.com/IlliaHalchun/life-game-cli)
I am newbie, than could do something wrong. Thank you in advance!
<img width="1273" alt="Screenshot 2023-01-06 at 02 54 30" src="https://user-images.githubusercontent.com/93126099/210955808-b16c2a8d-88c2-4b54-a472-8fd3207105ef.png">

**Comment by notaphplover** [comment]
I just run your code no error is thrown. Closing the issue now
