### ISSUE TITLE
vue (quasar) build results in reference error: 'cannot access Pn before initialization'

### ISSUE THREAD

**Issue by unknown1337** [remojansen/InversifyJS#1502]
Running my quasar project in dev mode works with inversify but building/ releasing it results in an error that seems somehow related to inversify

## Expected Behavior
expect my app to load when using the build package (it loads when using dev package).

## Current Behavior
1. `quasar serve .\dist\spa` 
2. opening browser + http://localhost:4000/#/
3. result: blank page + console error:
![image](https://user-images.githubusercontent.com/5968968/226846048-128f374a-2ad6-416a-9e5c-614dcbef19fd.png)

4. clicking on `inv.app.21684a42.js:666:16207` reveils
L43608:  `const vP = Pn.get(Xi);` and **later=NOK? **  L44440 till EOF:
``` 
const Pn = new E1({
    autoBindInjectable: !0
});
Pn.bind(Xi).toSelf();
Pn.bind(Or).toSelf();
Pn.bind(xr).toSelf();
Pn.bind(kr).toSelf();
Pn.bind(vo).toSelf();
Pn.bind(da).toSelf().inSingletonScope();
export {gs as A, Sn as H, Dt as R, xr as S, lF as a, F1 as b, nr as c, kr as d, Pn as e, Yy as f, Xi as g, vo as h, Fr as i, Cc as j, hF as k, mF as l, gF as m, _F as n, da as o, pF as p, ZP as q, dF as r, vF as s, yF as u};

```

5. if it helps L43731: `ou([nr(Xi)], xr.prototype, "_srvAuth", 2);` seems to reveil that  `const vP = Pn.get(Xi);` tries to inject my _srvAuth service

## Possible Solution
Need something to move the `const Pn=..` definition up indirectly as `Pn` is used before its being defined?

**Added later:**
in dev mode that already worked, I just received an error that was like: "appContainer is not defined/ does not exist". Refreshing the page made the error disappear, multiple refresh worked/ did not reveil the error again yet. So, is there maybe a non deterministic situation where the appcontainer is not defined yet but imported?

## Steps to Reproduce (for bugs)
'see current behaviour'

### The contents of inversify.app:
```
import 'reflect-metadata'; // only place where this reflect metadata is imported
import { Container } from 'inversify';
import { SrvAuth } from './services/srv_auth';
import { SrvHandleResp } from './services/srv_handleResp';
import { SrvUser } from './services/srv_user';
import { SrvRequest } from './services/srv_request';
import { SrvWorkspaces } from './services/srv_workspaces';
import { SrvReportSets } from './services/srv_reportSets';

const appContainer = new Container({ autoBindInjectable: true });
appContainer.bind<SrvAuth>(SrvAuth).toSelf();
appContainer.bind<SrvHandleResp>(SrvHandleResp).toSelf();
appContainer.bind<SrvUser>(SrvUser).toSelf();
appContainer.bind<SrvRequest>(SrvRequest).toSelf();
appContainer.bind<SrvWorkspaces>(SrvWorkspaces).toSelf();
appContainer.bind<SrvReportSets>(SrvReportSets).toSelf().inSingletonScope();
export { appContainer };

```
## Your Environment

Desktop Windows 11 Version 22H2 (Build 22621.1413)
Chrome 111.0.5563.65  
Build mode............. spa
 Pkg quasar............. v2.11.7
 Pkg @quasar/app-vite... v1.2.1
 Pkg vite............... v2.9.15
 Browser target......... es2019|edge88|firefox78|chrome87|safari13.1

### What could be going wrong? any ideas (as now Im kind of stuck :( ). THANKS!

**Comment by notaphplover** [comment]
Hey@unknown1337, please provide a repo with a minimal example to reproduce your issue

**Comment by unknown1337** [comment]
@notaphplover , I think I found the issue during the creation of a reproducable example. There  was a circular dependency in my code:
1. inversify.app.ts included some class
2. that class included appcontainer(.get()) in stead of @inject

Hope that this fixes the issue for me and possibly for others as well!

**Comment by notaphplover** [comment]
Great @unknown1337 :), I'll close the issue then
