### ISSUE TITLE
@inject not working

### ISSUE THREAD

**Issue by dstoyanoff** [remojansen/InversifyJS#1512]
I have turned around every corner of the internet about this issue, but couldn't find any solution.

I have configured Inversify in a project and everything seems to be working fine, besides trying to use `@inject` in a constructor or in a field.

When I resolve the dependencies using the container directly, it all works, which means the registration was successful, but the injection isn't.

## Expected Behavior
`@inject` should work or throw an error

## Current Behavior
The `@inject` decorator doesn't work and there are no errors in the console.

## Context
I am using NextJS () and the flow is triggered from a GraphQL API route.

## Your Environment

* Version used: 6.0.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v18.13.0
* Operating System and version (desktop or mobile): macOS 13.4
* NextJS: 13.4.3
* tsconfig:
```
compilerOptions: {
  // ...
   "experimentalDecorators": true,
   "emitDecoratorMetadata": true
}
```

**Comment by notaphplover** [comment]
@dstoyanoff can you provide a minimal example? Otherwise it's going to be close to impossible to reproduce your issue.

**Comment by dstoyanoff** [comment]
I will try to reproduce it in a minimal environment and post a link here, thanks.

**Comment by dstoyanoff** [comment]
https://github.com/dstoyanoff/inversify-inject-issue 

I've created the minimal reproduction. Run with `yarn dev`. I've exposed 3 different queries on the GraphQL endpoint (`api/graphql`) to showcase the different options:

// uses constructor injection (doesn't work)
```
query test {
    constructorTest
}
```

// uses field injection (doesn't work)
```
query test {
    fieldTest
}
```

// uses the container directly (works)
```
query test {
    containerGetTest
}
```

Let me know if anything else is needed

**Comment by dstoyanoff** [comment]
I actually found the problem. I had to instruct type-graphql about the use of the container and register my resolvers. Pushed a fix in the repo for reference
