### ISSUE TITLE
Container takes a long time to instantiate

### ISSUE THREAD

**Issue by mravey** [remojansen/InversifyJS#1524]
My container takes approximately 200ms to instantiate. The issue is that I instantiate a new one for each request, it allows me to inject a context with the current logged in user everywhere I want. Is there a way to speed up container instantiation or something I am doing wrong? Or is there another way to achieve what I want ?

**Comment by simhnna** [comment]
I'm also creating containers per request and they definitely don't take that long. Are you sure that container creation is the issue here?
