### ISSUE TITLE
Remove `browser` test suite

### ISSUE THREAD

**Issue by Jameskmonger** [remojansen/InversifyJS#1536]
The `browser` test suite is [no longer functional](https://github.com/inversify/InversifyJS/actions/runs/6279403787/job/17055096774?pr=1531)

[PhantomJS has not been supported since 2018](https://github.com/ariya/phantomjs/issues/15344) so I suggest we remove this test suite.

I'm not convinced there's much value in a specific set of browser tests anyway, given that our bundling mechanisms aren't necessarily the same as our users'.

**Comment by Jameskmonger** [comment]
Inviting feedback on this for the next few days, in the absence of any feedback I will be removing the faulty pipeline to unblock PR #1531 

cc @inversify/maintainers @inversify/collaborators @PodaruDragos @dcavanagh

**Comment by PodaruDragos** [comment]
+1 from me. If we ever need browser tests, we can always just use a different maintained framework like puppeteer.

**Comment by remojansen** [comment]
+1 For context when the browser tests were added was a time in which we still had IE and browser compatibility was still a very big issue. I don't think is relevant today.

**Comment by acald-creator** [comment]
+1 from me, no argument here

**Comment by Jameskmonger** [comment]
Thanks for the feedback @PodaruDragos @remojansen @acald-creator 

I will get on this this morning 😄
