### ISSUE TITLE
container.onNoMatchingBindingsFount or .onError

### ISSUE THREAD

**Issue by imcm7** [remojansen/InversifyJS#1537]
Why no something like `container.onNoMatchingBindingsFount(() => /* do something, throw an custom error*/)`.

**Comment by notaphplover** [comment]
A feature proposal should include a description with use cases and the motivation to implement the proposed feature. `inversify@6.2.0` will provide a `container.tryGet` methods in case you are interested in avoid throwing an error when no binding is found. Closing the issue now. Feel free to open a new one following the feature request template we provided.
