### ISSUE TITLE
Last release was on Oct 14, 2021

### ISSUE THREAD

**Issue by skalinkin** [remojansen/InversifyJS#1541]
Could someone provide an update on the project's current status? I've noticed that pull requests are being merged, but the last release was created two years ago.

**Comment by Jameskmonger** [comment]
Hey @skalinkin, just resolving some CI issues to get our pipeline working fully again, then I am to resume a release cadence for the project to resolve some of the outstanding issues

**Comment by skalinkin** [comment]
> Hey @skalinkin, just resolving some CI issues to get our pipeline working fully again, then I am to resume a release cadence for the project to resolve some of the outstanding issues

Thanks for response, let me know if you need any help.

**Comment by Jameskmonger** [comment]
thanks @skalinkin. You can see the prepared PR for the release here #1544

I will make the release this weekend, pending approval from the other maintainers.

**Comment by Jameskmonger** [comment]
Hi @skalinkin, pleased to say we have just published [Inversify v6.0.2](https://www.npmjs.com/package/inversify/v/6.0.2)

I will keep this issue open for a few days while I check the status of the other Inversify packages.

Thanks again for your support and patience!

**Comment by agorina** [comment]
Could you please update on the status of the support for this repository in general? Is it being maintained?

**Comment by PodaruDragos** [comment]
hey @agorina what are your concerns about this ? we are from time to time releasing new versions of `inversify`. Also I would say that the project is as mature and stable as it can be.

**Comment by agorina** [comment]
@PodaruDragos , thank you for the prompt response. I just wanted to get the confirmation that it is safe to keep using this module. There was a period of time when Typescript 5 issues have not been addressed but looks like it is all resolved now: https://stackoverflow.com/a/77415582 .

**Comment by Jameskmonger** [comment]
I'll close this issue as we are now working with a more regular release cycle. Please don't hesitate to reopen the issue or reach out to one of the contributors if you have any concerns.
