### ISSUE TITLE
Whether the inclusion size can be optimized

### ISSUE THREAD

**Issue by leonwangcn** [remojansen/InversifyJS#1547]
I used rollup for packing and the package was over 50 KB long, There's no other logic in my code

## Expected Behavior
The size of the packed inclusion can be reduced to less than 10KB

## Current Behavior
The inclusion size is 57KB after packing and compression

## Steps to Reproduce (for bugs)
My rollup profile is as follows

```
/** @type {import('rollup').RollupOptions} */
import resolve from '@rollup/plugin-node-resolve';
import babel from '@rollup/plugin-babel';
import typescript from "@rollup/plugin-typescript";
import terser from "@rollup/plugin-terser";

export default {
	input: 'src/unity/index.ts',
	output: {
		file: 'dist/index.js',
		format: 'esm'
	},
	plugins: [
		resolve(),
		typescript(),
		babel({
			extensions: ['.js', '.ts'],
			presets: ['@babel/preset-env', '@babel/preset-typescript'],
		}),
		terser()
	],
};
```

## Your Environment

    "@babel/core": "^7.23.2",
    "@babel/preset-env": "^7.23.2",
    "@babel/preset-typescript": "^7.23.2",
    "@rollup/plugin-babel": "^6.0.4",
    "@rollup/plugin-commonjs": "^25.0.7",
    "@rollup/plugin-node-resolve": "^15.2.3",
    "@rollup/plugin-terser": "^0.4.4",
    "@rollup/plugin-typescript": "^11.1.5",
    "rollup": "^4.3.0",
    "tslib": "^2.6.2"

**Comment by notaphplover** [comment]
It's sort of hard to tackle this issue. The scope is way too big. The way I see the library, it should support tree shaking in a nice way, I would like to see concrete exports that could be optimized.

> ## Expected Behavior
> The size of the packed inclusion can be reduced to less than 10KB

I don't think we will ever be in that point. 10KB is almost nothing.

I'm open to see concrete exports that might be optimized in the library, feel free to open an issue with a concrete example, the `inversify` exported module you found in your bundle and how or why it should be optimized.
