### ISSUE TITLE
Conflict test case found for type definition.

### ISSUE THREAD

**Issue by TotooriaHyperion** [remojansen/InversifyJS#1566]
I'm trying to improve BindingToSyntax type definition because it lost type check for toConstructor, toFactory to be compatible with type inferred from bind(XXX) ...etc

But I found conflict test cases:
![image](https://github.com/inversify/InversifyJS/assets/16434801/42bd4a46-7f54-4e7d-9689-f4a4150f5c28)

## Expected Behavior

types between BindingToSyntax<T> should be compatible with generic type param of toConstructor<T2>.

## Current Behavior

The right bottom example of BindingToSyntax\<T\> requires toConstructor(constructor: Newable\<T\>)
But the rest 3 examples of BindingToSyntax\<Newable\<T\>\> requires toConstructor(constructor: Newable\<T\>)

## Possible Solution

![image](https://github.com/inversify/InversifyJS/assets/16434801/9075d841-cd2a-422c-89ab-489660a79047)

This gives the toConstructor ability to infer the type from BindingToSyntax\<T\> if T is Newable or returns type never

But the Ninja test fails because it's using wrong types.

I need to change the test case of toConstructor\<Ninja\>(Ninja).

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

# Stack trace

**Comment by notaphplover** [comment]
Hey @TotooriaHyperion, I see, your proposal makes a lot of sense, but typescript is a bit tricky. I think there's an edge case we should try to cover:

Consider the following code example:

```ts
import { interfaces, LazyServiceIdentifer } from 'inversify';

type ExtendsLazyServiceIdentifier =
  LazyServiceIdentifer extends interfaces.Newable<LazyServiceIdentifer>
    ? true
    : false;
```
What type do you think is `ExtendsLazyServiceIdentifier`? The answer is, surprisingly `false`.

`tsc` declared types are not inferred as extending `new (...args: any[]) => infer T`, which is shocking.

I think I'll go to the `tsc` repo and ask why `T` is a `new (...args: any[]) => infer T` but only extends `new (...args: any[]) => infer T` when the class is not declared by `tsc`. Until that we will need to find a better solution.

EDIT: It seems https://stackoverflow.com/a/53056911 explains this weird behavior, I was not aware of this static-instance type duality of classes.

**Comment by notaphplover** [comment]
What about:

```ts
public toConstructor<T2 extends T>(
    constructor: interfaces.Newable<T2>,
  ): interfaces.BindingWhenOnSyntax<T>;
```
I think it would work nicely that way

**Comment by notaphplover** [comment]
Closing the issue as no response was provided.
