### ISSUE TITLE
`inversify-express-utils`: Not able to get the `withMiddleware` function installing latest version

### ISSUE THREAD

**Issue by marcosdipaolo** [remojansen/InversifyJS#1577]
Don't know if it's because you need to hook up a tag to the latest commit, but the `withMiddleware` function is still not available at latest `inversify-express-utils` version `6.4.6`

**Comment by rsaz** [comment]
Yes, it is a detected bug, it is part of the documentation : [withMiddleware](https://github.com/inversify/inversify-express-utils?tab=readme-ov-file#middleware-decorators) and we will investigate why is not getting exported and bundle in the package.

@notaphplover ping me when you can, this is simple to resolve, however I don't have access to.

**Comment by notaphplover** [comment]
> @notaphplover ping me when you can, this is simple to resolve, however I don't have access to. 

Hey @rsaz , what do you need access to?

**Comment by notaphplover** [comment]
`inversify-express-utils@6.4.7` is released! This should fix the issue. Feel free to ping me if not and I'll have it a look.

**Comment by rsaz** [comment]
> `inversify-express-utils@6.4.7` is released! This should fix the issue. Feel free to ping me if not and I'll have it a look.

Excellent, thanks @notaphplover . As I said, the issue was simple, the package wasn't built properly which left the functionality `withMiddleware` out of context.

Good job!
