### ISSUE TITLE
Error: Missing required @inject or @multiInject annotation in: argument 0 in class Ninja

### ISSUE THREAD

**Issue by cloudhx** [remojansen/InversifyJS#1582]
## Expected Behavior
InversifyJS allows your classes to have a direct dependency on other classes. When doing so you will need to use the @injectable decorator but you will not be required to use the @inject decorator.

## Current Behavior
When following the code here: https://github.com/inversify/InversifyJS/blob/master/wiki/classes_as_id.md, class that has direct dependencies on other classes cannot be create, error occurred: 

`Error: Missing required @inject or @multiInject annotation in: argument 0 in class Ninja.`

This error is mentioned in the same document as part of the Known Limitation: Classes as identifiers and circular dependencies, but without any circular dependencies it happens as well.

## Possible Solution

Using @inject decorator on constructor parameters makes it work.

## Steps to Reproduce (for bugs)

1. Create a node project using `npm init -y`
2. Install typescript and correctly configure it using `npx tsc --init` and inversify documentation
3. Install `inversify` and `reflect-metadata`
4. Create a typescript test file with the following code
```typescript
import "reflect-metadata";
import { Container, injectable, inject } from "inversify";

@injectable()
class Katana {
    public hit() {
        return "cut!";
    }
}

@injectable()
class Shuriken {
    public throw() {
        return "hit!";
    }
}

@injectable()
class Ninja {

    private _katana: Katana;
    private _shuriken: Shuriken;

    public constructor(katana: Katana, shuriken: Shuriken) {
        this._katana = katana;
        this._shuriken = shuriken;
    }

    public fight() { return this._katana.hit(); };
    public sneak() { return this._shuriken.throw(); };

}

var container = new Container();
container.bind<Ninja>(Ninja).to(Ninja);
container.bind<Katana>(Katana).to(Katana);
container.bind<Shuriken>(Shuriken).to(Shuriken);

var ninja = container.get<Ninja>(Ninja);
console.log(ninja.fight());
```
5. Run `npx tsx your test file`

## Context
Don't know what's going wrong, basically using the example from here: https://github.com/inversify/InversifyJS/blob/master/wiki/classes_as_id.md, but doesn't work.

## Your Environment

* Version used: `inversify@6.0.2` `typescript@5.6.2`
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v20.17.0
* Operating System and version (desktop or mobile): MacBook
* Link to your project:

# Stack trace

Error: Missing required @inject or @multiInject annotation in: argument 0 in class Ninja.
    at getConstructorArgsAsTarget (/Users/han/Documents/workspaces/temp/inversify-test/node_modules/inversify/lib/planning/reflection_utils.js:78:19)
    at getConstructorArgsAsTargets (/Users/han/Documents/workspaces/temp/inversify-test/node_modules/inversify/lib/planning/reflection_utils.js:90:22)
    at getTargets (/Users/han/Documents/workspaces/temp/inversify-test/node_modules/inversify/lib/planning/reflection_utils.js:56:30)
    at getDependencies (/Users/han/Documents/workspaces/temp/inversify-test/node_modules/inversify/lib/planning/reflection_utils.js:41:12)
    at /Users/han/Documents/workspaces/temp/inversify-test/node_modules/inversify/lib/planning/planner.js:124:71
    at Array.forEach (<anonymous>)
    at _createSubRequests (/Users/han/Documents/workspaces/temp/inversify-test/node_modules/inversify/lib/planning/planner.js:112:20)
    at plan (/Users/han/Documents/workspaces/temp/inversify-test/node_modules/inversify/lib/planning/planner.js:154:9)
    at /Users/han/Documents/workspaces/temp/inversify-test/node_modules/inversify/lib/container/container.js:626:46
    at Container._get (/Users/han/Documents/workspaces/temp/inversify-test/node_modules/inversify/lib/container/container.js:596:38)

**Comment by arrlancore** [comment]
you may need to share your tsconfig and you can try solution at [this known limitation](https://github.com/inversify/InversifyJS/blob/master/wiki/classes_as_id.md#known-limitation-classes-as-identifiers-and-circular-dependencies).

**Comment by goetas** [comment]
I'm having the same issue and my tsconfig
```
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
    ```

Node.js v18.18.2

**Comment by notaphplover** [comment]
Hey @cloudhx, @goetas , I just recreated it with a test and worked like a charm:

```ts
import { expect } from "chai";
import { Container, injectable } from "../../src/inversify";

describe("Issue 1582", () => {
  it("should instantiate object with injected constructor parameters", () => {
    @injectable()
    class Katana {
      public hit() {
        return "cut!";
      }
    }

    @injectable()
    class Shuriken {
      public throw() {
        return "hit!";
      }
    }

    @injectable()
    class Ninja {
      public constructor(public katana: Katana, public shuriken: Shuriken) {}

      public fight() {
        return this.katana.hit();
      }
      public sneak() {
        return this.shuriken.throw();
      }
    }

    const container = new Container();
    container.bind<Ninja>(Ninja).to(Ninja);
    container.bind<Katana>(Katana).to(Katana);
    container.bind<Shuriken>(Shuriken).to(Shuriken);

    const ninja = container.get<Ninja>(Ninja);

    expect(ninja.katana).to.deep.eq(new Katana());
    expect(ninja.shuriken).to.deep.eq(new Shuriken());
  });
});

```

Please try to recreate it in [codesandbox](https://codesandbox.io/) or in any other platform in which we can see the issue. We cannot identify nor solve the issue without recreating it

**Comment by notaphplover** [comment]
Closing as duplicate of #1555
