### ISSUE TITLE
"inversify-express-utils" has no exported member named 'withMiddleware'.

### ISSUE THREAD

**Issue by bombitmanbomb** [remojansen/InversifyJS#1583]
## Expected Behavior
import `withMiddleware` to create decorator middleware, [as described in the documentation](https://github.com/inversify/inversify-express-utils?tab=readme-ov-file#middleware-decorators).

## Current Behavior
```
"inversify-express-utils" has no exported member named 'withMiddleware'.
```

Currently using the latest available release (`v6.4.6`)

**Comment by notaphplover** [comment]
Closing as duplicate of #1577. It is a bug!

Please follow the above issue to check the resolution status
