### ISSUE TITLE
Can't inject class

### ISSUE THREAD

**Issue by Maxttier** [remojansen/InversifyJS#1600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/inversify/InversifyJS/issues/1598#issuecomment-2449343110 Error say `Error: Missing required @injectable annotation in: PlaygroundApp.`  not `The number of constructor arguments in a derived class must be >= than the number of constructor arguments of its base class.` like is wrote here https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md#inheritance

If i add unmanaged decorator to constructor parameters of PlaygroundApp nad derivated class the same error is

If i remove constructors all is the same 

```
<script lang="ts">
import { Container, inject, injectable, type interfaces } from 'inversify'
import { Component, Vue, Setup, toNative } from 'vue-facing-decorator'

container = new Container({ skipBaseClassChecks: true })
container.bind(Katana).toSelf()
container.bind(Shuriken).toSelf()
container.bind(Ninja).toSelf()
container.bind(PlaygroundApp).toSelf()

@injectable()
export class Katana {
  public hit() {
    return 'cut!'
  }
}

@injectable()
export class Shuriken {
  public throw() {
    return 'hit!'
  }
}

@injectable()
export class Ninja {
  public constructor(
    @inject(Katana) private katana: Katana,
  ) {}

  public fight() {
    return this.katana.hit()
  }
}

@Component({
})
@injectable()
class PlaygroundApp extends Vue {
  constructor(
    options: any,
    instance: any,
    @inject('Ninja')
    public ninja: Ninja
  ) {
    super(options, instance)
  }

  value!: number

  inc() {
    this.value++
  }
}
</script>

<template>
</template>
```

```
@Component({
})
@injectable()
class Page extends Vue {
// get PlaygroundApp here
}
```

### Steps to reproduce

Error: Missing required `@inject or @multiInject` annotation in: argument 0 in class PlaygroundApp.

if i use decorate it say what i decorated PlaygroundApp it multiple time.

Also i use decorate for Vue

Use container = new Container({ skipBaseClassChecks: true })

### Expected behavior

`@inject('Ninja')`    public ninja: Ninja in constructor to work
inject one vue component in another tor work (this is not not useful in that case)

### Package version

6.0.1

### Node.js version

20.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

https://github.com/mak7an/nuxt/blob/main/app.vue

**Comment by mak7an** [comment]
If `@unmanaged()` need to add to Vue how I will do that

**Comment by mak7an** [comment]
WORKAROUND E) Skip Base class @injectable checks

I set skipBaseClassChecks

**Comment by Maxttier** [comment]
Need to add `decorate(inject, Vue)` once not in App.vue and index.vue
