### ISSUE TITLE
Proper @preDestroy hooks ordering

### ISSUE THREAD

**Issue by Luluno01** [remojansen/InversifyJS#1606]
### Is there an existing proposal similar to this?

- [X] I have searched the existing proposals

### What are you proposing?

`preDestroy` hooks should be called (and awaited if they are `async`) in the order that respects the dependencies among the singletons.

The proposed destruction order is enforced by Spring framework: https://github.com/spring-projects/spring-framework/blob/2e6c8daec639b8194bf191b9f67056cde2a18f48/spring-beans/src/main/java/org/springframework/beans/factory/support/DefaultSingletonBeanRegistry.java#L643C29-L644.

### Is there any specific group of users that will benefit from this?

* Users who need ordered singleton destruction.
* Users who need the same behavior implemented by Spring framework when destructing inter-dependent singletons.

https://github.com/inversify/InversifyJS/issues/1602

### What problems are you trying to solve?

Suppose `ServiceB` depends on `ServiceA` (`ServiceB => ServiceA`) via `@inject(ServiceA)`. Both `ServiceA` and `ServiceB` register a `preDestroy` hook. For simplicity, both services have two states, namely `initialized` and `destroyed`, where the service is only usable in `initialized` state.

In such scenario, it is very natural for users to have such requirement: `ServiceB` is only `initialized` when `ServiceA` is also `initialized`. Therefore, when destroying `ServiceA` and `ServiceB`, the only valid destruction order is `ServiceB`, then `ServiceA`. Otherwise, `ServiceB` will be in `initialized` state when `ServiceA` is in `destroyed` state, which violate the aforementioned requirement.

### Do you have any references or examples that can illustrate your idea?

Given the following dependency graph, where an edge `ServiceB => ServiceA` is interpreted as `ServiceB` depends on `ServiceA` to function:

```mermaid
flowchart TD
    DatabaseService --> RemoteConfigService
    UserService --> RemoteConfigService
    UserService --> DatabaseService
    TeamService --> DatabaseService
```

Intuitively, when destroying the nodes in this graph, we should follow this order:

1. `UserService` and `TeamService` (destroy in parallel).
2. `DatabaseService`.
3. `RemoteConfigService`.

Also, we expect the destruction steps above to not overlap. Therefore, suppose all the services registered `preDestroy` hook on the method `destroy`, the equivalent destruction code is:

```TypeScript
await Promise.all([
  userService.destroy(),
  teamService.destroy(),
])
await databaseService.destroy()
await remoteConfigService.destroy()
```

Please refer to #1602 for another piece of example code.

### What type of idea is this?

Copy of existing idea: Similar idea exists and this is a copy

**Comment by notaphplover** [comment]
Thank you for submitting your proposal.

What you are proposing is a change in how current [deactivation handler](https://github.com/inversify/InversifyJS/blob/master/wiki/deactivation_handler.md) are resolved.

To summarize:

Given two services `A` and `B`, if `A` is an ancestor of `B`, the deactivation handler of B is invoked after the resolution of the deactivation handler of `A`.

Is this rule to be applied regardless of the distribution of these services in a [hierachy of containers](https://github.com/inversify/InversifyJS/blob/master/wiki/container_api.md#containercreatechildcontaineroptions-interfacescontaineroptions-container)?

**Comment by Luluno01** [comment]
> Thank you for submitting your proposal.
> 
> What you are proposing is a change in how current [deactivation handler](https://github.com/inversify/InversifyJS/blob/master/wiki/deactivation_handler.md) are resolved.
> 
> To summarize:
> 
> Given two services `A` and `B`, if `A` is an ancestor of `B`, the deactivation handler of B is invoked after the resolution of the deactivation handler of `A`.
> 
> Is this rule to be applied regardless of the distribution of these services in a [hierachy of containers](https://github.com/inversify/InversifyJS/blob/master/wiki/container_api.md#containercreatechildcontaineroptions-interfacescontaineroptions-container)?

Yes, I think the rule should be applied regardless of the container hierarchy. It is possible that the container hierarchy may enforce extra constraints, though.

**Comment by notaphplover** [comment]
> Yes, I think the rule should be applied regardless of the container hierarchy. It is possible that the container hierarchy may enforce extra constraints, though.

This might be trickier than what it appears to be at first glance.

Let's consider the following [example](https://codesandbox.io/p/devbox/inversify-containers-example-xv2t7v) for sample purposes:

It's just a hierarchy of services `A -> B -> C -> D`. The parent contianer provides some bindings so the hierachy goes `AImpl -> B1Impl -> C1Impl -> DImpl` and the child container some bindings so the hierachy in the child container is `AImpl -> B2Impl -> C2Impl -> DImpl`.

What should we do if we invoke `unbindAllAsync`?

If we asume all the classes have a deactivationHandler, we can only invoke `B2Impl._preDestroy` and `C2Impl._preDestroy` deactivation handlers since doing the same in `DImpl` or in `AImpl` might cause undesired side effects in the parent container.

If we cannot invoke `DImpl` or `AImpl` deactivation handlers, I don't see this feature request can move forward. I'm well aware it makes a lot of sense in your use case, but a feature request must have sense in every possible use case.

**Comment by Luluno01** [comment]
> > Yes, I think the rule should be applied regardless of the container hierarchy. It is possible that the container hierarchy may enforce extra constraints, though.
> 
> This might be trickier than what it appears to be at first glance.
> 
> Let's consider the following [example](https://codesandbox.io/p/devbox/inversify-containers-example-xv2t7v) for sample purposes:
> 
> It's just a hierarchy of services `A -> B -> C -> D`. The parent contianer provides some bindings so the hierachy goes `AImpl -> B1Impl -> C1Impl -> DImpl` and the child container some bindings so the hierachy in the child container is `AImpl -> B2Impl -> C2Impl -> DImpl`.
> 
> What should we do if we invoke `unbindAllAsync`?
> 
> If we asume all the classes have a deactivationHandler, we can only invoke `B2Impl._preDestroy` and `C2Impl._preDestroy` deactivation handlers since doing the same in `DImpl` or in `AImpl` might cause undesired side effects in the parent container.
> 
> If we cannot invoke `DImpl` or `AImpl` deactivation handlers, I don't see this feature request can move forward. I'm well aware it makes a lot of sense in your use case, but a feature request must have sense in every possible use case.

The example you attached isn't valid on my side. You probably forgot to run `npm run build` after adding `@preDestroy` hooks. I got this error:

> Error: @preDestroy error in class AImpl: Class cannot be instantiated in transient scope.

The direct cause to this is that **`@preDestroy` can only be used on singletons**. See https://github.com/inversify/InversifyJS/blob/5a32fd8fe28ef192b4f5fde901c377221e1c7bba/wiki/pre_destroy.md?plain=1#L3C149-L3C239.

I added `.inSingletonScope()` to all bindings so that all of services are instantiated and managed as singletons. As a result, we have `A -> B1 -> C1 -> D` in both containers (the child container is effectively a no-op). Hence, the only valid destruction order will always be `A`, `B1`, `C1`, and finally `D`.

**The two dependency graphs you mentioned is actually impossible** if `AImpl` is to be a singleton (`foo1 === foo2`). This is because the same singleton `AImpl` cannot have two different dependency hierarchies at the same time (there is no quantum superposition here LOL). By removing the `.inSingletonScope()` call and allowing multiple instances of `AImpl` (and of course the `@preDestroy` hook on `AImpl`), the example is runnable, and the output is:

> A -> B1 -> C1 -> D
> A -> B2 -> C2 -> D

Note that the two `A`s in the output are indeed two different instances of `AImpl` (`foo1 !== foo2`). Let's rename them as `A1` and `A2`, respectively. Now the full dependency graph looks like:

```mermaid
flowchart TD
    A1 --> B1
    B1 --> C1
    C1 --> D
    A2 --> B2
    B2 --> C2
    C2 --> D
```

And one possible valid destruction order is:

1. `A1` and `A2` (unordered).
2. `B1` and `B2` (unordered).
3. `C1` and `C2` (unordered).
4. `D`.

Let's take a step back, let's say you want `AImpl -> B1Impl -> C1Impl -> DImpl` and `AImpl -> B2Impl -> C2Impl -> DImpl` while all of them are singletons anyway. The only way to make this possible is to inject `B1Impl` and `B2Impl` to `AImpl` at the same time. Note that this effectively creates the whole hierarchy in the parent container when you get it. In this case, the dependency graph looks like:

```mermaid
flowchart TD
    A --> B1
    B1 --> C1
    C1 --> D
    A --> B2
    B2 --> C2
    C2 --> D
```

And one possible valid destruction order is:

1. `A`.
2. `B1` and `B2` (unordered).
3. `C1` and `C2` (unordered).
4. `D`.

**Comment by notaphplover** [comment]
My bad, I forgot to bind services in singleton scope. Maybe the `A -> B -> C -> D` example is not a great counter example.

I just updated our example with a simple one: this time there a simple `A -> B` dependency.

```mermaid
flowchart TD
    A --> B
```

My main concern is: calling container.unbindAll() simply unbinds all the bindings of a container. If `A` and `B` are in different container, calling `childContainer.unbindAll()` should result in unbinding `A` and not `B`. That's my main concern here. All the destructuring orders you propose in the previous example are not possible because not of all services are in the same container.

**Comment by gitroll-dev** [comment]
> ... calling childContainer.unbindAll() should result in unbinding `A` and not `B`.

You mean `A` is in `childContainer` and `B` is in `parentContainer`, while `A` is created after `B` and holds a reference to `B`, right? Because `A -> B`, i.e., `A` depends on `B`, so `A` should always be destroyed before `B`, which does not conflict with your statement of "calling childContainer.unbindAll() should result in unbinding `A` and not `B`". Am I missing anything here?

**Comment by Luluno01** [comment]
> ... calling `childContainer.unbindAll()` should result in unbinding `A` and not `B`.

You mean `A` is in `childContainer` and `B` is in `parentContainer`, while `A` is created after `B` and holds a reference to `B`, right? By the proposed rule, because `A -> B`, i.e., `A` depends on `B`, so `A` should always be destroyed before `B`, which does not conflict with your statement of "calling childContainer.unbindAll() should result in unbinding `A` and not `B`".

Am I missing anything here? Or did you mean calling `unbindAll` on `parentContainer` without unbinding on `childContainer`? Is that even legit?

**Comment by notaphplover** [comment]
Hey, I mean the code in the [example](https://codesandbox.io/p/devbox/inversify-containers-example-xv2t7v).

> Am I missing anything here? Or did you mean calling unbindAll on parentContainer without unbinding on childContainer? Is that even legit?

I mean the following:
- Calling `container.unbindAll()` unbinds `BImpl` and not `AImpl`.
- Calling `childContainer.unbindAll()` unbinds `AImpl` and not `BImpl`.
- You're allowed to call `container.unbindAll()` before `childContainer.unbindAll()`.
- You're allowed to call `childContainer.unbindAll` before `container.unbindAll()`.

This way it's sort of hard to control the order in which `AImpl` and `BImpl` are disposed.

Tbh this is not the behavior I like most. So much freedom is pain in the back to maintain and a lot of trouble to analyze features like the one you're proposing. But we cannot break the current behavior without a very good reason to do so.

**Comment by Luluno01** [comment]
> Hey, I mean the code in the [example](https://codesandbox.io/p/devbox/inversify-containers-example-xv2t7v).
> 
> > Am I missing anything here? Or did you mean calling unbindAll on parentContainer without unbinding on childContainer? Is that even legit?
> 
> I mean the following:
> 
> * Calling `container.unbindAll()` unbinds `BImpl` and not `AImpl`.
> * Calling `childContainer.unbindAll()` unbinds `AImpl` and not `BImpl`.
> * You're allowed to call `container.unbindAll()` before `childContainer.unbindAll()`.
> * You're allowed to call `childContainer.unbindAll` before `container.unbindAll()`.
> 
> This way it's sort of hard to control the order in which `AImpl` and `BImpl` are disposed.
> 
> Tbh this is not the behavior I like most. So much freedom is pain in the back to maintain and a lot of trouble to analyze features like the one you're proposing. But we cannot break the current behavior without a very good reason to do so.

Ah I see. Inversify does allow calling `parentContainer.unbindAll` before `childContainer.unbindAll`, which makes it tricky for us to enforce the proposed rule. In Spring this is not a problem, because its IoC containers do not have a hierarchical relationship.

What about throwing an error when you are trying to destroy singletons that still have dependants? This makes sense to me as if someone is doing so, they are most likely breaking the dependants. Otherwise, calling `parentContainer.unbindAll` works as usual. That said, I understand this is still a breaking change.

To avoid introducing breaking change like this, we can add a `strictOrder: boolean = false` parameter to the `preDestroy` annotation... But yes, this also sounds like lots of complexity. \*sigh

**Comment by notaphplover** [comment]
> What about throwing an error when you are trying to destroy singletons that still have dependants?

The thing is, there're might be reasons to allow it. The container is just a catalog of bindings, it's perfectly fine for this catalog to be incomplete by design. Developers are the ones who have the freedom (and therefore the responsibility) of making sense. It might be ok to unbind a container if that's what the developer want to do, he might make sense later adding new bindings.

**Comment by notaphplover** [comment]
I understand this feature is proposed to be used in a certain use case, am I right? Are we sure we cannot find a way with the current `inversify` features?

**Comment by Luluno01** [comment]
Yes, of course you can allow anything in theory. But I don't think it's safe or a common/good practice for developers to do so. So instead of breaking an existing API of high degree of freedom, could we add a new one like `destroy`, which implies "no re-binding later" and so unbinding `B` first as in `A => B` is most likely a mistake?

**Comment by Luluno01** [comment]
> I understand this feature is proposed to be used in a certain use case, am I right? Are we sure we cannot find a way with the current `inversify` features?

To the best of what I can think of, you will have to manually and explicitly destroy the singletons in the correct order.

**Comment by notaphplover** [comment]
EDIT: I actually closed the issue by a missclick... I need to change my mouse.

> Yes, of course you can allow anything in theory. But I don't think it's safe or a common/good practice for developers to do so. So instead of breaking an existing API of high degree of freedom, could we add a new one like `destroy`, which implies "no re-binding later" and so unbinding `B` first as in `A => B` is most likely a mistake?

It would be against the current design since class hierachies are distributed among different containers and containers only manage their own bindings. Whatever is unbound can be bound later. I'm afraid the container is not a garbage collector nor handles the responsibility of handling dispose operations in a way a GC does. It's totally safe to unbind A and B in any order, javascript GC is making sure of that destroying instances only when no references point at them.

I can see the benefits of your approach and I do love Spring `preDestroy` approach, but the architechtural approach is way different than `inversify` one since early stages of the project. This feature request would imply a drastical change in the design of the container I'm afraid.

I'm thinking in workarounds, but they're not trivial at all. Is it so hard to manually destroy singletons in the right order?

- You might have a `ApplicationShutdownService` service with all the services you want to destroy and manually call them in the right order in the `@preDestroy` targeted method of the `ApplicationShutdownService`.

- You could do some magic with the `ReflectMetadata` API to manage what you want to do:

### Basic approach:

Given a class Foo, you could probably implement the `@disposable` class decorator wich receives a function to be invoked.

`@disposable` defines `ReflectMetadata` associated to `Foo` with the function to be invoked and a boolean indicating if the call has been made.

A `dispose` function would be implemented, receiving an instance.
1. Dispose would find metadata associated to the instance type. If so, and the boolean flag is set to false, the dispose function function defined in the metadata would be invoked and the boolean flag would be set to true.
2. Dispose would traverse instance properties and call dispose(property).

This is just a basic approach, you would need to refine this if you want to build some sort of library to do this.

Once you have this implemented, simply gather root disposable services the way you want (you could mark them with a `DisposableRoot` service identifier, for example, and fetch them with an inversify container) and call `dispose` on them.

Yeah, I know, lots of work.

**Comment by Luluno01** [comment]
Of course, it's feasible to call the destroy functions in an explicit order.

> You might have a `ApplicationShutdownService` service with all the services you want to destroy and manually call them in the right order in the `@preDestroy` targeted method of the `ApplicationShutdownService`.

If you achieve this by doing something like this:

```
const userService = container.get('UserService')
const teamService = container.get('TeamService')
const databaseService = container.get('DatabaseService')
const remoteConfigService = container.get('RemoteConfigService')

await Promise.all([
  userService.destroy(),
  teamService.destroy(),
])
await databaseService.destroy()
await remoteConfigService.destroy()
```

The cons are obvious:

* Destruction dependencies are manually resolved, which is inefficient, error-prone and it distracts the developers' focus away from the core business logics.
* This is not a grey-boxed or black-boxed implementation, which
  * Assumes a certain binding configuration. For example, `UserService` is assumed to be bound to the implementation that actually depends on the exact implementation bound to `DatabaseService`.
  * Lowers the maintainability.
  * Increases the probability of bugs should the dependency relationships change in future software revisions.

> You could do some magic with the `ReflectMetadata` API to manage what you want to do:

You are basically suggesting making another library that reinvents the entire Inversify library and adding what I want. This is because "destructing inter-dependent instances in the correct order" requires declaring the dependencies explicitly in the first place, and that is exactly what dependency injection libraries provide. In fact, they are more like a dual by nature. Therefore, if we were to implement this feature via `ReflectMetadata` magic without reinventing what Inversify already has, we will either have to add our own decorators and metadata, or hook into Inversify's decorators and metadata. The former results in `@inject('ServiceA') @dependsOn('ServiceA') private serviceA: ServiceA`, while the latter has to "hack" Inversify or re-resolve the dependencies on its own. Either way is extremely ugly and unmaintainable.

Since the DI library already has all the information to do this automatically, I believe the best place to implement this feature is the DI library itself.

---

And yes, I do understand the complexity required to implement this feature in current Inversify, but I still insist we should have this feature provided by the DI library itself.

**Comment by notaphplover** [comment]
> You are basically suggesting making another library that reinvents the entire Inversify library and adding what I want. This is because "destructing inter-dependent instances in the correct order" requires declaring the dependencies explicitly in the first place, and that is exactly what dependency injection libraries provide. In fact, they are more like a dual by nature. Therefore, if we were to implement this feature via ReflectMetadata magic without reinventing what Inversify already has, we will either have to add our own decorators and metadata, or hook into Inversify's decorators and metadata. The former results in @inject('ServiceA') @dependsOn('ServiceA') private serviceA: ServiceA, while the latter has to "hack" Inversify or re-resolve the dependencies on its own. Either way is extremely ugly and unmaintainable.

It would be totally independent from `inversify`, you only need to rely on your own metadata. It's just a suggestion, you're free to take it or not. I would personally choose the manual approach.

> And yes, I do understand the complexity required to implement this feature in current Inversify, but I still insist we should have this feature provided by the DI library itself.

I'm afraid it's not a choice, I already ellaborated it in my previous comment.

**Comment by Luluno01** [comment]
> > You are basically suggesting making another library that reinvents the entire Inversify library and adding what I want. This is because "destructing inter-dependent instances in the correct order" requires declaring the dependencies explicitly in the first place, and that is exactly what dependency injection libraries provide. In fact, they are more like a dual by nature. Therefore, if we were to implement this feature via ReflectMetadata magic without reinventing what Inversify already has, we will either have to add our own decorators and metadata, or hook into Inversify's decorators and metadata. The former results in @Inject('ServiceA') @dependsOn('ServiceA') private serviceA: ServiceA, while the latter has to "hack" Inversify or re-resolve the dependencies on its own. Either way is extremely ugly and unmaintainable.
> 
> It would be totally independent from `inversify`, you only need to rely on your own metadata. It's just a suggestion, you're free to take it or not. I would personally choose the manual approach.
> 
> > And yes, I do understand the complexity required to implement this feature in current Inversify, but I still insist we should have this feature provided by the DI library itself.
> 
> I'm afraid it's not a choice, I already ellaborated it in my previous comment.

I see. Thanks for your reply!

**Comment by notaphplover** [comment]
You're very welcome. I will proceed to close the issue. If there's anything else you might want to discuss, feel free to ping me :smiley:

**Comment by Luluno01** [comment]
I realized I don't have to use `container.unbindAllAsync` provided by Inversify. Here is my own destroyer (or disposer?) [Depi](https://github.com/unlib-js/depi). Feel free to take a look. 🫡
