### ISSUE TITLE
[6.1.4] getTargetsFromMetadataProviders() throws a TypeError

### ISSUE THREAD

**Issue by ffMathy** [remojansen/InversifyJS#1610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I get the following error now all of a sudden. Quite critical out of a minor release, which happened automatically because I have `^6.0.3` specified.

It means it actually installs `6.1.1` now for some of our developers, leading to this bug.

```
TypeError: Cannot read properties of undefined (reading 'kind')
   ❯ getTagets node_modules/@inversifyjs/core/src/legacyTarget/calculations/getTargetsFromMetadataProviders.ts:39:31
   ❯ getBaseClassDependencyCount node_modules/inversify/lib/planning/reflection_utils.js:39:61
   ❯ node_modules/inversify/lib/planning/planner.js:144:99
   ❯ _createSubRequests node_modules/inversify/lib/planning/planner.js:129:20
   ❯ plan node_modules/inversify/lib/planning/planner.js:172:9
   ❯ node_modules/inversify/lib/container/container.js:663:46
   ❯ Container._get node_modules/inversify/lib/container/container.js:633:38
   ❯ Container._getButThrowIfAsync node_modules/inversify/lib/container/container.js:636:27
   ❯ Container.get node_modules/inversify/lib/container/container.js:385:21
   ❯ Binding.dynamicValue node_modules/inversify/lib/syntax/binding_to_syntax.js:112:38
   ❯ node_modules/inversify/lib/resolution/resolver.js:99:52
   ❯ tryAndThrowErrorIfStackOverflow node_modules/inversify/lib/utils/exceptions.js:35:16
   ❯ _resolveFactoryFromBinding node_modules/inversify/lib/resolution/resolver.js:98:61
   ❯ _getResolvedFromBinding node_modules/inversify/lib/resolution/resolver.js:120:22
   ❯ node_modules/inversify/lib/resolution/resolver.js:135:22
   ❯ _resolveInScope node_modules/inversify/lib/resolution/resolver.js:129:14
   ❯ _resolveBinding node_modules/inversify/lib/resolution/resolver.js:134:12
   ❯ node_modules/inversify/lib/resolution/resolver.js:92:20
   ❯ resolve node_modules/inversify/lib/resolution/resolver.js:238:12
   ❯ node_modules/inversify/lib/container/container.js:665:49
   ❯ Container._get node_modules/inversify/lib/container/container.js:633:38
   ❯ Container._getButThrowIfAsync node_modules/inversify/lib/container/container.js:636:27
   ❯ Container.get node_modules/inversify/lib/container/container.js:385:21
```

I tried removing my `injectable` attributes as well, to no avail.

### Expected behavior

I expect it not to throw an exception.

### Package version

6.1.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by notaphplover** [comment]
Hey @ffMathy can you please add a minimal reproduction repro?

**Comment by ffMathy** [comment]
I cannot unfortunately due to NDA, and we are very busy due to Christmas coming up soon. We've just pinned 6.0.3 for now. Just wanted to inform of it.

**Comment by ffMathy** [comment]
Not sure if it's relevant, but it happens via tests that I run with Vitest.

Here's my Vitest config:

```
import fs from 'node:fs';
import path from 'node:path';
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import dotenv from 'dotenv';
import { v4 } from 'uuid';
import { defineConfig } from 'vitest/config';
import type { Reporter } from 'vitest/reporters';

/**
 * This reporter makes sure that the total list of tests in the whole suite is being written to a file, so we know which ones are no longer present, and need to have
 * their snapshot files removed.
 */
class SnapshotTestReporter implements Reporter {
  private context: any;

  onInit(context: any): void {
    this.context = context;
  }

  async onPathsCollected(files: string[] | undefined) {
    const filesBeingRun = files || [];
    const allTestFiles = await this.context.getTestFilepaths();
  }
}

export default defineConfig({
  plugins: [nxViteTsPaths()],
  cacheDir: './node_modules/.vitest',
  logLevel: 'info',
  test: {
    env: {
      ...dotenv.parse(fs.readFileSync(path.join(__dirname, '.env.testing'))),
      VITEST: v4(),
    },
    isolate: false,
    pool: 'forks',
    maxConcurrency: 2,
    maxWorkers: 10,
    minWorkers: 10,
    watch: false,
    testTimeout: 60_000 * 10,
    hookTimeout: 60_000 * 10,
    retry: process.env.DEPENDABOT ? 3 : process.env.GITHUB_PATH ? 1 : 0,
    globals: true,
    globalSetup: ['./jest.global-setup.ts'],
    setupFiles: ['./jest.setup.ts'],
    reporters: ['default', new SnapshotTestReporter()],
    coverage: {
      enabled: true,
      provider: 'v8',
    },
    environment: 'node',
    include: ['src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    exclude: ['dist/*'],
  },
  esbuild: {
    target: 'es2022',
  },
});
```

It's an NX monorepo.

**Comment by ffMathy** [comment]
My `jest.setup.ts` then imports reflect metadata:

```
import 'reflect-metadata';
...
```

**Comment by notaphplover** [comment]
> I cannot unfortunately due to NDA, and we are very busy due to Christmas coming up soon. We've just pinned 6.0.3 for now. Just wanted to inform of it.

I'm not asking to share your source code, just a small piece of code that fails. It can be code fragment that has the same issue without being your source code. If everything is breaking it's probably sort of easy to figure it out the issue with that.

Having a look at the trace, it's related to the `constructorArguments` generated by a metadata reader. Are you using [custom metadata readers](https://github.com/inversify/InversifyJS/blob/master/wiki/middleware.md#custom-metadata-reader)? The container seems to be strugling to fetch metadata in your case.

**Comment by ffMathy** [comment]
> I'm not asking to share your source code, just a small piece of code that fails. It can be code fragment that has the same issue without being your source code. If everything is breaking it's probably sort of easy to figure it out the issue with that.

Well, that's the thing. If I just create a simple example, it doesn't fail. So narrowing down what causes it would take some time. And that's time I do not have yet. I will have more time in Q1 for this.

> Having a look at the trace, it's related to the constructorArguments generated by a metadata reader. Are you using [custom metadata readers](https://github.com/inversify/InversifyJS/blob/master/wiki/middleware.md#custom-metadata-reader)? The container seems to be strugling to fetch metadata in your case.

Nope, not using custom metadata reader unfortunately.

**Comment by notaphplover** [comment]
> Well, that's the thing. If I just create a simple example, it doesn't fail. So narrowing down what causes it would take some time. And that's time I do not have yet. I will have more time in Q1 for this.

All right. I'll give it a loop and try to recreate it locally. It's gonna be challeging on my side though: the affected flow is so simple I cannot figure out the way to break it without asuming something is wrong in the emitted typescript metadata.

If I come up with something I'll publish a beta so you can try it. Unfortunately, the only workaround I can suggest is pinning to `inversify@6.0.3`.

**Comment by ffMathy** [comment]
I am not sure if Vitest even builds my project, or just somehow runs the TypeScript directly. It's fast enough at least to convince me that no compilation is going on. But not sure.

**Comment by notaphplover** [comment]
I've been thinking what can possibly be the cause of the issue. The only conclussions I reached is metadata is not properly fetched, maybe one of your classes is missing an `@inject` decorator and `emitDecoratorMetadata` typescript option is not enabled in that scenario.

I'm working to provide a more friendly error in that scenario, I'll release a new version so you can gather more info of this error.

**Comment by notaphplover** [comment]
Hey @ffMathy I just published a [v6.1.2-beta.0](https://www.npmjs.com/package/inversify/v/6.1.2-beta.0) prerelese. If you have some time it would be great if you could try it. You should see a better error description that hopefully can give us some hints of what's going on.

**Comment by ffMathy** [comment]
The latest release (6.1.4) works. Thank you.

**Comment by ffMathy** [comment]
Sorry, said this too soon. It was because I hadn't restarted the Vitest worker process. It still happens.

Here's the new error in 6.1.4:

```
Found unexpected missing metadata on type "BaseFtrackMaterialBuilder" at constructor indexes "0".

Are you using @inject, @multiInject or @unmanaged decorators at those indexes?

If you're using typescript and want to rely on auto injection, set "emitDecoratorMetadata" compiler option to true
    at assertConstructorMetadataArrayFilled (file:///workspaces/WATS/node_modules/@inversifyjs/core/lib/esm/webpack:/@inversifyjs/core/src/metadata/calculations/assertConstructorMetadataArrayFilled.ts:23:11)
    at getClassMetadataConstructorArgumentsFromMetadataReader (file:///workspaces/WATS/node_modules/@inversifyjs/core/lib/esm/webpack:/@inversifyjs/core/src/metadata/calculations/getClassMetadataConstructorArgumentsFromMetadataReader.ts:48:3)
    at getClassMetadataFromMetadataReader (file:///workspaces/WATS/node_modules/@inversifyjs/core/lib/esm/webpack:/@inversifyjs/core/src/metadata/calculations/getClassMetadataFromMetadataReader.ts:22:7)
    at getClassMetadata (file:///workspaces/WATS/node_modules/@inversifyjs/core/lib/esm/webpack:/@inversifyjs/core/src/legacyTarget/calculations/getTargets.ts:22:11)
    at file:///workspaces/WATS/node_modules/@inversifyjs/core/lib/esm/webpack:/@inversifyjs/core/src/legacyTarget/calculations/getTargetsFromMetadataProviders.ts:17:42
    at getBaseClassDependencyCount (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/planning/reflection_utils.ts:10:23)
    at forEach (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/planning/planner.ts:119:48)
    at Array.forEach (<anonymous>)
    at _createSubRequests (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/planning/planner.ts:104:20)
    at plan (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/planning/planner.ts:147:9)
    at this (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/container/container.ts:641:27)
    at t._get (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/container/container.ts:611:16)
    at t._getButThrowIfAsync (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/container/container.ts:614:27)
    at t.get (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/container/container.ts:359:21)
    at t.factoryDetails [as dynamicValue] (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/syntax/binding_to_syntax.ts:86:38)
    at tryAndThrowErrorIfStackOverflow (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/resolution/resolver.ts:73:16)
    at _resolveFactoryFromBinding (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/resolution/resolver.ts:72:12)
    at _getResolvedFromBinding (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/resolution/resolver.ts:94:22)
    at resolveFromBinding (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/resolution/resolver.ts:109:22)
    at _resolveInScope (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/resolution/resolver.ts:103:14)
    at _resolveBinding (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/resolution/resolver.ts:108:12)
    at resolveRequestFunction (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/resolution/resolver.ts:66:20)
    at resolve (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/resolution/resolver.ts:212:12)
    at this (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/container/container.ts:643:26)
    at t._get (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/container/container.ts:611:16)
    at t._getButThrowIfAsync (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/container/container.ts:614:27)
    at t.get (file:///workspaces/WATS/node_modules/inversify/es/webpack:/inversify/src/container/container.ts:359:21)
```

**Comment by notaphplover** [comment]
Hey @ffMathy, ok, I think that rings a bell!

I understand this is a base class, and it's first constructor parameter is not decorated, is that so? If it is, consider [docs](https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md#workaround-a-use-the-unmanaged-decorator) as reference. Base classes requires their params to be injected as well, if you don't want to handle then you probably want to rely on the `@unmanaged` decorator as the error description suggests.

**Comment by ffMathy** [comment]
That's the weird part. Indeed it's a base class, but all parameters do indeed have a "inject" attribute.

What's weird is that if I downgrade the package to the previous version without code changes, it just works.

**Comment by notaphplover** [comment]
I see, ok, we've made a progress though.

I think you should be able to recreate the issue with that class. The key is probably to recreate your case with vitest. If you manage to do it, just create a recreation repro or link a code sandbox and I'll have it a look.

I think the bundling is the key, I see `vitest` seems to be using `webpack` under the scenes. Having said that, `inversify@6.1.4` ESM build is working with several bundlers, I'd be suprised if it's not working with `webpack`. 

Until I got the repro there's not much I can do :(, if you are injecting the parameter then there should be no way to end up with the issue you're facing.

**Comment by ffMathy** [comment]
I am an idiot. It did indeed seem like the first argument of a base class didn't have an attribute. It was easy to miss because there were two levels of inheritance.

Not sure why this was fine before though.

**Comment by notaphplover** [comment]
@ffMathy don't worry about it man, I honestly believe you're not an idiot at all. We are human and make mistakes. That's all :smiley:

> Not sure why this was fine before though.

I think inversify was allowing this in the previous versions, but was not the expected behavior. Docs state `@unmanaged` should be used to inject these kind of params. If I recall properly, the container has a `skipBaseClassChecks` option that would allow not injecting decorators in base classes.

May I close the issue or is there any wrong behavior in these regard?

**Comment by ffMathy** [comment]
You've been great here. Thanks.

Yes, it may be closed!

I think the explicit strict behavior is good. It's a nice thing.

Thanks for the understanding.

**Comment by notaphplover** [comment]
You're very welcome, closing the issue then :)
