### ISSUE TITLE
No matching bindings found for serviceIdentifier: Function

### ISSUE THREAD

**Issue by svenjacobs** [remojansen/InversifyJS#1621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We tried to update from `6.0.2` to `6.1.2` but suddenly get the following error.

```
Error: No matching bindings found for serviceIdentifier: Function
    at _validateActiveBindingCount (/Users/sven.jacobs/Developer/Workspace/xyz/node_modules/inversify/lib/planning/planner.js:99:23)
    at _getActiveBindings (/Users/sven.jacobs/Developer/Workspace/xyz/node_modules/inversify/lib/planning/planner.js:73:5)
    at _createSubRequests (/Users/sven.jacobs/Developer/Workspace/xyz/node_modules/inversify/lib/planning/planner.js:126:26)
    at /Users/sven.jacobs/Developer/Workspace/xyz/node_modules/inversify/lib/planning/planner.js:151:17
    at Array.forEach (<anonymous>)
    at /Users/sven.jacobs/Developer/Workspace/xyz/node_modules/inversify/lib/planning/planner.js:150:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (/Users/sven.jacobs/Developer/Workspace/xyz/node_modules/inversify/lib/planning/planner.js:129:20)
    at plan (/Users/sven.jacobs/Developer/Workspace/xyz/node_modules/inversify/lib/planning/planner.js:172:9)
    at /Users/sven.jacobs/Developer/Workspace/xyz/node_modules/inversify/lib/container/container.js:663:46
```

Unfortunately it's unclear which module / binding now is problematic.

### Expected behavior

The update to `6.1.2` does not produce this error.

### Package version

6.1.2

### Node.js version

18.20.4

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by svenjacobs** [comment]
I have to correct myself. This problem already exists since version `6.0.3`.

**Comment by notaphplover** [comment]
Hey @svenjacobs please provide a minimum reproduction of the issue in order to have it a look.

**Comment by svenjacobs** [comment]
Unfortunately this is a complex project and I don't have a minimal reproducible project (yet). Also, the error message doesn't give me any hints where in our code the problem could originate so I have no idea where to start looking 🙁

**Comment by notaphplover** [comment]
If I had to guess, it seems one of your params of a certain service is a function with no `@inject` decorator:

```ts
  it('Should throw when a function has a missing @inject annotation', () => {
    interface Sword {
      damage: number;
    }

    @injectable()
    class Katana implements Sword {
      public readonly damage: number = 20;
    }

    @injectable()
    class Ninja {
      public katana: Katana;

      constructor(katanaFactory: () => Katana) {
        this.katana = katanaFactory();
      }
    }

    const container: Container = new Container();
    container.bind<Ninja>('Ninja').to(Ninja);
    container.bind<Katana>('Katana').to(Katana);
    container.bind<Katana>('Factory<Katana>').to(Katana);

    const throwFunction: () => void = () => {
      plan(
        new MetadataReader(),
        container,
        false,
        TargetTypeEnum.Variable,
        'Ninja',
      );
    };

    expect(throwFunction).to.throw(
      'No matching bindings found for serviceIdentifier: Function',
    );
  });
```

But it's really hard to tell without having a look at the code :(

**Comment by notaphplover** [comment]
Hey @svenjacobs, I just released `inversify@6.1.4-beta.0` with better error descriptions in your use case. Now, inversify should fail like this:

```ts
  it('Should throw when a function has a missing @inject annotation', () => {
    interface Sword {
      damage: number;
    }

    @injectable()
    class Katana implements Sword {
      public readonly damage: number = 20;
    }

    @injectable()
    class Ninja {
      public katana: Katana;

      constructor(katanaFactory: () => Katana) {
        this.katana = katanaFactory();
      }
    }

    const container: Container = new Container();
    container.bind<Ninja>('Ninja').to(Ninja);
    container.bind<Katana>('Katana').to(Katana);
    container.bind<Katana>('Factory<Katana>').to(Katana);

    const throwFunction: () => void = () => {
      plan(
        new MetadataReader(),
        container,
        false,
        TargetTypeEnum.Variable,
        'Ninja',
      );
    };

    expect(throwFunction).to.throw(
      `No matching bindings found for serviceIdentifier: Function
Trying to resolve bindings for "Ninja"`,
    );
  });
```

Could you try targeting this version? Hopefully we can narrow down this way the scope of the affected source code.

**Comment by svenjacobs** [comment]
Thanks a lot for the beta version with the additional output! This helped in finding the root cause. So we have a class like this:

```typescript
@injectable()
export default class SomeClass {
    constructor(
        private readonly isProdEnvironment: () => boolean = () => true
    ) {}
}
```

The class takes a function as a constructor argument **but** the argument has a default value.
This used to work in `6.0.2` but is broken in later versions. Is this intended?

**Comment by notaphplover** [comment]
It should not work on `inversify@6.0.2`. I mean, if it worked, it was not intended. As [docs](https://github.com/inversify/InversifyJS/blob/master/wiki/optional_dependencies.md) states, optional dependencies should have an `@optional()` decorator attached to them:

```ts
@injectable()
export default class SomeClass {
    constructor(
        @inject("your-service-id") @optional()
        private readonly isProdEnvironment: () => boolean = () => true
    ) {}
}
```

If you are not expecting inversify to inject the service and you'll be managing the injection of the service, `@unmanaged` is probably what you're looking for:

```ts
@injectable()
export default class SomeClass {
    constructor(
        @unmanaged()
        private readonly isProdEnvironment: () => boolean = () => true
    ) {}
}
```

That should solve the issue. I'll leave the issue open. If that solves your issue, feel free to close it :smiley: .

**Comment by svenjacobs** [comment]
Thank you! Adding `@unmanaged()` fixed the issue for us with Inversify `6.0.3+`.

**Comment by danilofuchs** [comment]
@notaphplover I also faced this issue and adding `unmanaged` fixed it.

Do you think it is viable to add an specific error message when the arguments of an object cannot be filled by inversify?

`No matching bindings found for serviceIdentifier` got me thinking I forgot to bind the object somehow

**Comment by notaphplover** [comment]
> Do you think it is viable to add an specific error message when the arguments of an object cannot be filled by inversify

Hey @danilofuchs, I don't see a way to distinguish a missing injection from a missing unmanaged injection, so I don't think it's viable. Maybe I'm missing something
