### ISSUE TITLE
[6.1.0] TypeScript error when `Container.bind` is used with mongoose `Model`

### ISSUE THREAD

**Issue by patricktree** [remojansen/InversifyJS#1630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When `inversify@6.1.0` `Container.bind` is used with a `mongoose@7.8.2` `Model`, a TypeScript compilation error occurs:

 ```txt
> tsc

src/index.mts:14:38 - error TS2379: Argument of type 'Model<Blah, {}, {}, {}, Document<unknown, {}, Blah> & Blah & Required<{ _id: unknown; }>, any>' is not assignable to parameter of type 'Document<unknown, {}, Blah> & Blah & Required<{ _id: unknown; }>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
  Type 'Model<Blah, {}, {}, {}, Document<unknown, {}, Blah> & Blah & Required<{ _id: unknown; }>, any>' is missing the following properties from type 'Document<unknown, {}, Blah>': $assertPopulated, $clone, $getAllSubdocs, $ignore, and 37 more.

14 container.bind(asdf).toConstantValue(asdf);
                                        ~~~~

  src/index.mts:14:38
    14 container.bind(asdf).toConstantValue(asdf);
                                            ~~~~
    Did you mean to use 'new' with this expression?


Found 1 error in src/index.mts:14
```

This is not the case when `inversify` is downgraded to `6.0.3`, so the regression must have happened in this changeset: https://github.com/inversify/InversifyJS/compare/v6.0.3...v6.1.0

### Steps to reproduce

1. Open https://codesandbox.io/p/devbox/4ttd39
2. `npm ci`
3. `npm run build`

### Expected behavior

No TypeScript compilation error

### Package version

6.1.0

### Node.js version

20.9.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by patricktree** [comment]
I wonder if this is related to #1629

**Comment by notaphplover** [comment]
Hey @pkerschbaum, I just tested against `inversify@6.1.3` (the latest version) in your code sandbox and it's working. Can you double check?

**Comment by patricktree** [comment]
Oh it is true that my repro doesn't throw a compilation error with `inversify@6.1.3`, but we @hokify have also with this version an error.  
I will try to create a better repro!

**Comment by patricktree** [comment]
I was able to reproduce it with 6.1.3 - the importing module must be a CJS module in order for the error to occur.  
new repro: https://codesandbox.io/p/devbox/https-github-com-inversify-inversifyjs-issues-1630-6-1-3-42rmy7

I think I found out what the cause is: mongoose `Model` defines a `new` constructor signature which does NOT return a `Model`, it returns a `THydratedDocument`.  
`inversify@6.1.3` pulls out that `THydratedDocument` and `.toConstantValue` expects such a thing then.  
I wonder if that behavior of inversify is correct, or not.

**Comment by notaphplover** [comment]
I see, it's interesting. Sometimes typescript inference is crazy.

Let's have a look at the code sample:

```ts
import { Container } from "inversify";

import { Model } from "mongoose";

const container = new Container({
  autoBindInjectable: true,
  defaultScope: "Singleton",
});

const asdf = "asdf" as unknown as Model<unknown>;

container.bind(asdf).toConstantValue(asdf);
```

Let's focus on the last line:

```ts
container.bind(asdf).toConstantValue(asdf);
```

When installing `inversify@6.0.3`, typescript infers `T` in `bind<T>` is `any`.
When installing `inversify@6.0.3`, typescript infers `T` in `bind<T>` is `Document<unknown, {}, unknown> & { _id: ObjectId }`.

### Why?
Tbh, I am not sure why tsc infers any when installing `inversify@6.0.3`.

If you try this:

```ts
const bsdg: interfaces.ServiceIdentifier<
  Document<unknown, {}, unknown> & { _id: ObjectId }
> = asdf;
```
It works in both `inversify@6.0.3` and `inversify@6.1.3`, therefore, infering `T` as `Document<unknown, {}, unknown> & { _id: ObjectId }` is a valid choice when installing `inversify@6.0.3`.

Sometimes typesctript inference is crazy, specially when handling complex types like `mongoose` ones.

In these cases, I would suggest you to help the compiler:

```ts
container.bind<Model<unknown>>(asdf).toConstantValue(asdf);
``` 

This way, when tsc detects ambiguity in cases like this one, you're covered. There's not too much I can do unless I'm missing something. I'll close the issue now. Feel free to comment on this thread, if you think there's something we can do I'll reopen the issue.

**Comment by notaphplover** [comment]
I've been thinking about this issue, and you were right! The absence of `Abstract<T>` was causing the "breaking change".

Consider the following code with `inversify@6.1.3`:

```ts
import { interfaces } from "inversify";

import { Model } from "mongoose";

const asdf = "asdf" as unknown as Model<unknown>;

type ServiceId<T> = interfaces.Abstract<T> | interfaces.ServiceIdentifier<T>;

function get<T>(serviceId: ServiceId<T>): ServiceId<T> {
  return serviceId;
}

const bsdg = get(asdf);
```

`bsdg` is evaluated as `any` cause typescript understands its an `Abstract<any>`.

If we remove `Abstract<T>` from `ServiceId`:

```ts
import { interfaces } from "inversify";

import { Model } from "mongoose";

const asdf = "asdf" as unknown as Model<unknown>;

type ServiceId<T> = interfaces.ServiceIdentifier<T>;

function get<T>(serviceId: ServiceId<T>): ServiceId<T> {
  return serviceId;
}

const bsdg = get(asdf);
```
Now, `bsdg` is evaluated as `ServiceId<Document<unknown, {}, unknown> & { _id: Types.ObjectId; }>` because it no longers can be inferred as an `Abstract<any>`.

Having said that, I really don't like `Abstract` as part of a service identifier. It's basically saying "if your prototype can be inferred as T, you are instantiating objects fulfilling T" which is not necessarily the case. Prototypes are really tricky, and I don't want a `ServiceIdentifier` which makes these kind of assumptions, that was the reason to replace it with `Function`. I see there behavior is not the same, but if `ServiceIdentifier<T>` is inferred with `T`, then ServiceIdentifier must instantiate objects fulfilling `T`.

That's the main reason to replace `Abstract`. I really try not to break types, I'm well aware of how tedious it is, but in this case I consider it more a fix than breaking change due to the reason I mentioned.

**Comment by patricktree** [comment]
> I've been thinking about this issue, and you were right! The absence of `Abstract<T>` was causing the "breaking change".
> 
> Consider the following code with `inversify@6.1.3`:
> 
> ```ts
> import { interfaces } from "inversify";
> 
> import { Model } from "mongoose";
> 
> const asdf = "asdf" as unknown as Model<unknown>;
> 
> type ServiceId<T> = interfaces.Abstract<T> | interfaces.ServiceIdentifier<T>;
> 
> function get<T>(serviceId: ServiceId<T>): ServiceId<T> {
>   return serviceId;
> }
> 
> const bsdg = get(asdf);
> ```
> 
> `bsdg` is evaluated as `any` cause typescript understands its an `Abstract<any>`.
> 
> If we remove `Abstract<T>` from `ServiceId`:
> 
> ```ts
> import { interfaces } from "inversify";
> 
> import { Model } from "mongoose";
> 
> const asdf = "asdf" as unknown as Model<unknown>;
> 
> type ServiceId<T> = interfaces.ServiceIdentifier<T>;
> 
> function get<T>(serviceId: ServiceId<T>): ServiceId<T> {
>   return serviceId;
> }
> 
> const bsdg = get(asdf);
> ```
> 
> Now, `bsdg` is evaluated as `ServiceId<Document<unknown, {}, unknown> & { _id: Types.ObjectId; }>` because it no longers can be inferred as an `Abstract<any>`.
> 
> Having said that, I really don't like `Abstract` as part of a service identifier. It's basically saying "if your prototype can be inferred as T, you are instantiating objects fulfilling T" which is not necessarily the case. Prototypes are really tricky, and I don't want a `ServiceIdentifier` which makes these kind of assumptions, that was the reason to replace it with `Function`. I see there behavior is not the same, but if `ServiceIdentifier<T>` is inferred with `T`, then ServiceIdentifier must instantiate objects fulfilling `T`.
> 
> That's the main reason to replace `Abstract`. I really try not to break types, I'm well aware of how tedious it is, but in this case I consider it more a fix than breaking change due to the reason I mentioned.

Thanks for your detailed answer!  
I agree to your analysis that the new types are better (and that not breaking types in non-major releases is tricky :P).

One last question: For the mongoose case, I think best is to explicitly type it to get rid of the error, like this in the repro:

```typescript
container.bind<Model<unknown>>(asdf).toConstantValue(asdf);
````

Do you agree?

(FYI this is legacy code in our @hokify codebase and we want to challenge that way of doing DI anyways; because, doing `new Model` produces a `THydratedDocument`, so we should NOT set the value of this service identifier to something which is no `THydratedDocument`)

**Comment by notaphplover** [comment]
You're very welcome :smiley: .

> One last question: For the mongoose case, I think best is to explicitly type it to get rid of the error, like this in the repro:
> ```ts
> container.bind<Model<unknown>>(asdf).toConstantValue(asdf);
> ```
> Do you agree?

Absolutely, if the type is complex, better safe than sorry.
