### ISSUE TITLE
Inversify is not compatible with ESM

### ISSUE THREAD

**Issue by abgonzalez93** [remojansen/InversifyJS#1642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![imagen](https://github.com/user-attachments/assets/a55e1417-fa36-4960-89ba-fba58425923f)

**Module "inversify" not found. Did you intend to set the "moduleResolution" option to "nodenext" or add aliases to the "paths" option?ts(2792)**

### Expected behavior

Expected inversify to be compatible with ESM

### Package version

6.1.4

### Node.js version

22.11.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by abgonzalez93** [comment]
**UPDATED:** It's working after updating `tsconfig.json`

![imagen](https://github.com/user-attachments/assets/17cbcc7f-1935-41d4-b500-d1657b563d86)

The problem now is that types are not getting updated. App runs. Everything is perfect. But in this case, `mongoRepository` should be a `MongoRepository` type, not any type.

![imagen](https://github.com/user-attachments/assets/24d8b5ea-4475-4c1e-93dc-73533856069d)

**Comment by abgonzalez93** [comment]
If we change `module` from `tsconfig.json` to `commonjs`, inversify returns types correctly. But I dont want CommonJS. I need ESM.

![imagen](https://github.com/user-attachments/assets/92e42171-8805-4f5a-bed7-3212d4854cf7)

**Comment by notaphplover** [comment]
Hey @abgonzalez93, can you provide a minimum reproduction repo? Consider sharing a [code sandbox](https://codesandbox.io/) or a reproduction repository.

**Comment by abgonzalez93** [comment]
Ok, nevermind. I got to solve it changing this `tsconfig.json` options.

`module `as` ESNext`
`moduleResolution` as `bundler`

![imagen](https://github.com/user-attachments/assets/1d391768-31f2-4f9f-a6a6-44d70265bbc3)
