### ISSUE TITLE
Container.getAll ignores binding when condition

### ISSUE THREAD

**Issue by sebastien-comeau** [remojansen/InversifyJS#1670]
### Current behavior

The `container.getAll` method appears to ignore the `when` binding conditions. As demonstrated in the unit tests, when the `storage-config` value is set to a specific configuration (e.g., `'disk'` or `'redis'`) and `container.getAll<Storage>('storage')` is called, it returns all bindings for the `storage` service (e.g., `['disk-storage', 'redis-storage']`), regardless of the specified `storage-config` value.

### Steps to reproduce

Unit tests reproducing the current behavior.
https://stackblitz.com/edit/vitest-dev-vitest-pw5pnz?file=test%2Fbasic.test.ts

### Expected behavior

When the `storage-config` value is set to a specific configuration (`'disk'` or `'redis'`) and `container.getAll<Storage>('storage')` is called:

- For `'disk'`, only the `'disk-storage'` binding should be resolved.
- For `'redis'`, only the `'redis-storage'` binding should be resolved.

### Package version

6.1.6

**Comment by notaphplover** [comment]
Hey @sebastien-comeau, yeah, this is so confusing!

Ok, `container.getAll()` gets all the bindings regardless of their constraints. I'm working on the next major to provide a better developer experience. This is one of the several issues to solve.

The code is working as expected. Having said that, I find the current behavior super confusing. I am not going to break the existing behavior, but we might provide an optional parameter to `container.getAll` and `container.getAllAsync`:

```ts

export interface GetAllOptions {
  enforceBindingConstraints?: boolean;
}

export interface Container {
  public getAll<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>, options?: GetAllOptions): T[];
  public async getAllAsync<T>(
    serviceIdentifier: interfaces.ServiceIdentifier<T>,
    options?: GetAllOptions,
  ): Promise<T[]>;
}
```

This way we could provide the behavior you're looking for without breaking the current one.

**Comment by sebastien-comeau** [comment]
@notaphplover sounds good! Are you considering adding `container.tryGet` or `container.find` to retrieve a service when constraints is `true` and return `undefined` when it's `false` #566? Currently, in my custom container provider, `AppContainerProvider`, I handle this by catching a thrown `Error` and returning `undefined`. It might also be beneficial to introduce custom `Error` classes for more precise behavior targeting.

```ts
export class DefaultAppContainerProvider implements AppContainerProvider {
  private readonly log: Logger;

  constructor(private readonly container: interfaces.Container) {
    const logFactory = container.get(TYPES.factories.LogFactory);
    this.log = logFactory.createLogger('DefaultAppContainerProvider');
  }

  find<T>(serviceIdentifier: ServiceIdentifier<T>): T | undefined {
    this.log.trace('Finding service for service identifier: %s', serviceIdentifier);
    try {
      return this.container.get(serviceIdentifier);
    } catch (error) {
      this.log.trace('Service not found for service identifier: %s; returning undefined. Error: %o', serviceIdentifier, error);
      return undefined;
    }
  }

  get<T>(serviceIdentifier: ServiceIdentifier<T>): T {
    this.log.trace('Get service for service identifier: %s', serviceIdentifier);
    return this.container.get(serviceIdentifier);
  }
}
```

**Comment by notaphplover** [comment]
> Are you considering adding container.tryGet or container.find to retrieve a service when constraints is true and return undefined when it's false https://github.com/inversify/InversifyJS/issues/566?

I could have it a look, yeah. It's sort of easy to provide that feature, I can probably go for it tomorrow.

**Comment by notaphplover** [comment]
`inversify@6.2.0-beta.0` is released with this feature! I'm closing the issue now, if you find the behavior not to be the expected one just ping me and I'll reopen the issue. Of course, a `6.2.0` version will be released, probably on the next week.
